/**
 * This file was auto-generated by @openapi-qraft/cli.
 * Do not make direct changes to the file.
 */

import { qraftAPIClient, type APIBasicClientServices, type CreateAPIBasicClientOptions, type CreateAPIClientOptions, type CreateAPIQueryClientOptions } from "@openapi-qraft/react";
import * as callbacks from "@openapi-qraft/react/callbacks/index";
import { services, type Services } from "./services/index.js";
export function createAPIClient(options: CreateAPIQueryClientOptions): Services;
export function createAPIClient(options: CreateAPIBasicClientOptions): APIBasicClientServices<Services, ServiceMethods>;
export function createAPIClient(options: CreateAPIClientOptions): Services | APIBasicClientServices<Services, ServiceMethods> {
    return qraftAPIClient<Services, ServiceMethods>(services, callbacks, options);
}
type ServiceMethods = typeof callbacks;
