/**
 * This file was auto-generated by @openapi-qraft/cli.
 * Do not make direct changes to the file.
 */

import type { APIBasicClientServices, APIBasicQueryClientServices, APIDefaultQueryClientServices, APIQueryClientServices, APIUtilityClientServices, CreateAPIBasicClientOptions, CreateAPIBasicQueryClientOptions, CreateAPIClientOptions, CreateAPIQueryClientOptions } from "@openapi-qraft/react";
import * as allCallbacks from "@openapi-qraft/react/callbacks/index";
import { qraftAPIClient } from "@openapi-qraft/react";
import { services } from "./services/index.js";
export function createAPIClient<Callbacks extends AllCallbacks>(options: CreateAPIQueryClientOptions, callbacks?: Callbacks): APIDefaultQueryClientServices<Services>;
export function createAPIClient<Callbacks extends Partial<AllCallbacks> = AllCallbacks>(options: CreateAPIBasicQueryClientOptions, callbacks?: Callbacks): APIBasicQueryClientServices<Services, Callbacks>;
export function createAPIClient<Callbacks extends Partial<AllCallbacks> = AllCallbacks>(options: CreateAPIBasicClientOptions, callbacks?: Callbacks): APIBasicClientServices<Services, Callbacks>;
export function createAPIClient<Callbacks extends Partial<AllCallbacks> = AllCallbacks>(callbacks?: Callbacks): APIUtilityClientServices<Services, Callbacks>;
export function createAPIClient<Callbacks extends Partial<AllCallbacks> = AllCallbacks>(callbacksOrOptions?: CreateAPIClientOptions | Callbacks, callbacks: Callbacks = allCallbacks as Callbacks): APIDefaultQueryClientServices<Services> | APIQueryClientServices<Services, Callbacks> | APIBasicQueryClientServices<Services, Callbacks> | APIBasicClientServices<Services, Callbacks> | APIUtilityClientServices<Services, Callbacks> {
    if (!callbacksOrOptions)
        return qraftAPIClient(services, callbacks);
    if ("requestFn" in callbacksOrOptions)
        return qraftAPIClient(services, callbacks, callbacksOrOptions);
    if ("queryClient" in callbacksOrOptions)
        return qraftAPIClient(services, callbacks, callbacksOrOptions);
    return qraftAPIClient(services, callbacksOrOptions);
}
type AllCallbacks = typeof allCallbacks;
type Services = typeof services;
