/**
 * This file was auto-generated by @openapi-qraft/cli.
 * Do not make direct changes to the file.
 */

import type { paths } from "../../openapi.js";
import type { ServiceOperationQuery, ServiceOperationMutation } from "@openapi-qraft/react";
export interface ApprovalPoliciesService {
    /**
     * @summary Get an approval policy by ID
     * @description Retrieve a specific approval policy.
     */
    getApprovalPoliciesId: ServiceOperationQuery<{
        method: "get";
        url: "/approval_policies/{approval_policy_id}";
        security: [
            "partnerToken"
        ];
    }, paths["/approval_policies/{approval_policy_id}"]["get"]["responses"]["200"]["content"]["application/json"], paths["/approval_policies/{approval_policy_id}"]["get"]["parameters"], paths["/approval_policies/{approval_policy_id}"]["get"]["responses"]["401"]["content"]["application/json"] | paths["/approval_policies/{approval_policy_id}"]["get"]["responses"]["422"]["content"]["application/json"] | paths["/approval_policies/{approval_policy_id}"]["get"]["responses"]["default"]["content"]["application/json"]>;
    /**
     * @summary Delete an approval policy
     * @description Delete an existing approval policy.
     */
    deleteApprovalPoliciesId: ServiceOperationMutation<{
        method: "delete";
        url: "/approval_policies/{approval_policy_id}";
        security: [
            "HTTPBearer"
        ];
    }, undefined, paths["/approval_policies/{approval_policy_id}"]["delete"]["responses"]["200"]["content"]["application/json"], paths["/approval_policies/{approval_policy_id}"]["delete"]["parameters"], paths["/approval_policies/{approval_policy_id}"]["delete"]["responses"]["401"]["content"]["application/json"] | paths["/approval_policies/{approval_policy_id}"]["delete"]["responses"]["422"]["content"]["application/json"] | paths["/approval_policies/{approval_policy_id}"]["delete"]["responses"]["default"]["content"]["application/json"]>;
    /**
     * @summary Update an approval policy
     * @description Update an existing approval policy.
     */
    patchApprovalPoliciesId: ServiceOperationMutation<{
        method: "patch";
        url: "/approval_policies/{approval_policy_id}";
        mediaType: "application/json";
        security: [
            "HTTPBearer"
        ];
    }, NonNullable<paths["/approval_policies/{approval_policy_id}"]["patch"]["requestBody"]>["content"]["application/json"], paths["/approval_policies/{approval_policy_id}"]["patch"]["responses"]["200"]["content"]["application/json"], paths["/approval_policies/{approval_policy_id}"]["patch"]["parameters"], paths["/approval_policies/{approval_policy_id}"]["patch"]["responses"]["401"]["content"]["application/json"] | paths["/approval_policies/{approval_policy_id}"]["patch"]["responses"]["422"]["content"]["application/json"] | paths["/approval_policies/{approval_policy_id}"]["patch"]["responses"]["default"]["content"]["application/json"]>;
}
export const approvalPoliciesService: {
    /**
     * @summary Get an approval policy by ID
     * @description Retrieve a specific approval policy.
     */
    getApprovalPoliciesId: {
        schema: {
            method: "get";
            url: "/approval_policies/{approval_policy_id}";
            security: [
                "partnerToken"
            ];
        };
    };
    /**
     * @summary Delete an approval policy
     * @description Delete an existing approval policy.
     */
    deleteApprovalPoliciesId: {
        schema: {
            method: "delete";
            url: "/approval_policies/{approval_policy_id}";
            security: [
                "HTTPBearer"
            ];
        };
    };
    /**
     * @summary Update an approval policy
     * @description Update an existing approval policy.
     */
    patchApprovalPoliciesId: {
        schema: {
            method: "patch";
            url: "/approval_policies/{approval_policy_id}";
            mediaType: "application/json";
            security: [
                "HTTPBearer"
            ];
        };
    };
} = {
    getApprovalPoliciesId: {
        schema: {
            method: "get",
            url: "/approval_policies/{approval_policy_id}",
            security: ["partnerToken"]
        }
    },
    deleteApprovalPoliciesId: {
        schema: {
            method: "delete",
            url: "/approval_policies/{approval_policy_id}",
            security: ["HTTPBearer"]
        }
    },
    patchApprovalPoliciesId: {
        schema: {
            method: "patch",
            url: "/approval_policies/{approval_policy_id}",
            mediaType: "application/json",
            security: ["HTTPBearer"]
        }
    }
};
