/**
 * This file was auto-generated by @openapi-qraft/cli.
 * Do not make direct changes to the file.
 */

import type { paths } from "../../openapi.js";
import type { AreAllOptional, InvalidateQueryFilters, MutationFiltersByMutationKey, MutationFiltersByParameters, MutationVariables, OperationInfiniteData, PartialParameters, QueryFiltersByParameters, QueryFiltersByQueryKey, QueryFnOptionsByParameters, QueryFnOptionsByQueryKey, RequestFnResponse, ServiceOperationEnsureInfiniteQueryDataOptions, ServiceOperationEnsureQueryDataOptions, ServiceOperationFetchInfiniteQueryOptions, ServiceOperationFetchQueryOptions, ServiceOperationInfiniteQueryKey, ServiceOperationMutationFnOptions, ServiceOperationMutationKey, ServiceOperationQueryKey, ServiceOperationUseMutationOptions, UseQueryOptionsForUseQueries, UseQueryOptionsForUseSuspenseQuery, WithOptional } from "@openapi-qraft/tanstack-query-react-types";
import type { CancelOptions, InfiniteQueryPageParamsOptions, InvalidateOptions, Mutation, MutationState, NoInfer, QueryState, RefetchOptions, ResetOptions, SetDataOptions, Updater } from "@tanstack/query-core";
import type { DefinedInitialDataInfiniteOptions, DefinedInitialDataOptions, DefinedUseInfiniteQueryResult, DefinedUseQueryResult, UndefinedInitialDataInfiniteOptions, UndefinedInitialDataOptions, UseInfiniteQueryResult, UseMutationResult, UseQueryResult, UseSuspenseInfiniteQueryOptions, UseSuspenseInfiniteQueryResult, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
export interface ApprovalPoliciesService {
    /**
     * @summary Get an approval policy by ID
     * @description Retrieve a specific approval policy.
     */
    getApprovalPoliciesId: {
        /**
         * @summary Get an approval policy by ID
         * @description Retrieve a specific approval policy.
         */
        cancelQueries<TInfinite extends boolean = false>(filters?: QueryFiltersByParameters<GetApprovalPoliciesIdSchema, GetApprovalPoliciesIdData, TInfinite, GetApprovalPoliciesIdParameters, GetApprovalPoliciesIdError> | QueryFiltersByQueryKey<GetApprovalPoliciesIdSchema, GetApprovalPoliciesIdData, TInfinite, GetApprovalPoliciesIdParameters, GetApprovalPoliciesIdError>, options?: CancelOptions): Promise<void>;
        /**
         * @summary Get an approval policy by ID
         * @description Retrieve a specific approval policy.
         */
        getQueryKey(parameters: GetApprovalPoliciesIdParameters): ServiceOperationQueryKey<GetApprovalPoliciesIdSchema, GetApprovalPoliciesIdParameters>;
        /**
         * Performs asynchronous data fetching, manages loading states and error handling.
         *
         * @summary Get an approval policy by ID
         * @description Retrieve a specific approval policy.
         * @see {@link https://openapi-qraft.github.io/openapi-qraft/docs/hooks/useQuery|`useQuery(...)` documentation}
         * @example Query with parameters
         * ```ts
         * const { data, isLoading } = qraft.approvalPoliciesService.getApprovalPoliciesId.useQuery({
         *     header: {
         *         "x-monite-version": "2023-06-04",
         *         "x-monite-entity-id": xMoniteEntityId
         *     },
         *     path: {
         *         approval_policy_id: approvalPolicyId
         *     },
         *     query: {
         *         items_order: itemsOrder
         *     }
         * })
         * ```
         */
        useQuery<TData = GetApprovalPoliciesIdData>(parameters: ServiceOperationQueryKey<GetApprovalPoliciesIdSchema, GetApprovalPoliciesIdParameters> | (GetApprovalPoliciesIdParameters), options?: Omit<UndefinedInitialDataOptions<GetApprovalPoliciesIdData, GetApprovalPoliciesIdError, TData, ServiceOperationQueryKey<GetApprovalPoliciesIdSchema, GetApprovalPoliciesIdParameters>>, "queryKey">): UseQueryResult<TData, GetApprovalPoliciesIdError | Error>;
        /**
         * Performs asynchronous data fetching, manages loading states and error handling.
         *
         * @summary Get an approval policy by ID
         * @description Retrieve a specific approval policy.
         * @see {@link https://openapi-qraft.github.io/openapi-qraft/docs/hooks/useQuery|`useQuery(...)` documentation}
         * @example Query with parameters
         * ```ts
         * const { data, isLoading } = qraft.approvalPoliciesService.getApprovalPoliciesId.useQuery({
         *     header: {
         *         "x-monite-version": "2023-06-04",
         *         "x-monite-entity-id": xMoniteEntityId
         *     },
         *     path: {
         *         approval_policy_id: approvalPolicyId
         *     },
         *     query: {
         *         items_order: itemsOrder
         *     }
         * })
         * ```
         */
        useQuery<TData = GetApprovalPoliciesIdData>(parameters: ServiceOperationQueryKey<GetApprovalPoliciesIdSchema, GetApprovalPoliciesIdParameters> | (GetApprovalPoliciesIdParameters), options: Omit<DefinedInitialDataOptions<GetApprovalPoliciesIdData, GetApprovalPoliciesIdError, TData, ServiceOperationQueryKey<GetApprovalPoliciesIdSchema, GetApprovalPoliciesIdParameters>>, "queryKey">): DefinedUseQueryResult<TData, GetApprovalPoliciesIdError | Error>;
        /**
         * @summary Get an approval policy by ID
         * @description Retrieve a specific approval policy.
         */
        fetchInfiniteQuery<TPageParam extends GetApprovalPoliciesIdParameters>(options: ServiceOperationFetchInfiniteQueryOptions<GetApprovalPoliciesIdSchema, GetApprovalPoliciesIdData, GetApprovalPoliciesIdParameters, TPageParam, GetApprovalPoliciesIdError>): Promise<OperationInfiniteData<GetApprovalPoliciesIdData, GetApprovalPoliciesIdParameters>>;
        /**
         * @summary Get an approval policy by ID
         * @description Retrieve a specific approval policy.
         */
        prefetchInfiniteQuery<TPageParam extends GetApprovalPoliciesIdParameters>(options: ServiceOperationFetchInfiniteQueryOptions<GetApprovalPoliciesIdSchema, GetApprovalPoliciesIdData, GetApprovalPoliciesIdParameters, TPageParam, GetApprovalPoliciesIdError>): Promise<void>;
        /**
         * @summary Get an approval policy by ID
         * @description Retrieve a specific approval policy.
         */
        ensureInfiniteQueryData<TPageParam extends GetApprovalPoliciesIdParameters>(options: ServiceOperationEnsureInfiniteQueryDataOptions<GetApprovalPoliciesIdSchema, GetApprovalPoliciesIdData, GetApprovalPoliciesIdParameters, TPageParam, GetApprovalPoliciesIdError>): Promise<OperationInfiniteData<GetApprovalPoliciesIdData, GetApprovalPoliciesIdParameters>>;
        /**
         * @summary Get an approval policy by ID
         * @description Retrieve a specific approval policy.
         */
        fetchQuery(options: ServiceOperationFetchQueryOptions<GetApprovalPoliciesIdSchema, GetApprovalPoliciesIdData, GetApprovalPoliciesIdParameters, GetApprovalPoliciesIdError>): Promise<GetApprovalPoliciesIdData>;
        /**
         * @summary Get an approval policy by ID
         * @description Retrieve a specific approval policy.
         */
        prefetchQuery(options: ServiceOperationFetchQueryOptions<GetApprovalPoliciesIdSchema, GetApprovalPoliciesIdData, GetApprovalPoliciesIdParameters, GetApprovalPoliciesIdError>): Promise<void>;
        /**
         * @summary Get an approval policy by ID
         * @description Retrieve a specific approval policy.
         */
        ensureQueryData(options: ServiceOperationEnsureQueryDataOptions<GetApprovalPoliciesIdSchema, GetApprovalPoliciesIdData, GetApprovalPoliciesIdParameters, GetApprovalPoliciesIdError>): Promise<GetApprovalPoliciesIdData>;
        /**
         * @summary Get an approval policy by ID
         * @description Retrieve a specific approval policy.
         */
        getInfiniteQueryData(parameters: ServiceOperationInfiniteQueryKey<GetApprovalPoliciesIdSchema, GetApprovalPoliciesIdParameters> | (GetApprovalPoliciesIdParameters)): OperationInfiniteData<GetApprovalPoliciesIdData, GetApprovalPoliciesIdParameters> | undefined;
        /**
         * @summary Get an approval policy by ID
         * @description Retrieve a specific approval policy.
         */
        getQueriesData<TInfinite extends boolean = false>(filters?: QueryFiltersByParameters<GetApprovalPoliciesIdSchema, GetApprovalPoliciesIdData, TInfinite, GetApprovalPoliciesIdParameters, GetApprovalPoliciesIdError> | QueryFiltersByQueryKey<GetApprovalPoliciesIdSchema, GetApprovalPoliciesIdData, TInfinite, GetApprovalPoliciesIdParameters, GetApprovalPoliciesIdError>): TInfinite extends true ? Array<[
            queryKey: ServiceOperationInfiniteQueryKey<GetApprovalPoliciesIdSchema, GetApprovalPoliciesIdParameters>,
            data: NoInfer<OperationInfiniteData<GetApprovalPoliciesIdData, GetApprovalPoliciesIdParameters>> | undefined
        ]> : Array<[
            queryKey: ServiceOperationQueryKey<GetApprovalPoliciesIdSchema, GetApprovalPoliciesIdParameters>,
            data: GetApprovalPoliciesIdData | undefined
        ]>;
        /**
         * @summary Get an approval policy by ID
         * @description Retrieve a specific approval policy.
         */
        getQueryData(parameters: ServiceOperationQueryKey<GetApprovalPoliciesIdSchema, GetApprovalPoliciesIdParameters> | (GetApprovalPoliciesIdParameters)): GetApprovalPoliciesIdData | undefined;
        /**
         * @summary Get an approval policy by ID
         * @description Retrieve a specific approval policy.
         */
        getQueryState(parameters: ServiceOperationQueryKey<GetApprovalPoliciesIdSchema, GetApprovalPoliciesIdParameters> | (GetApprovalPoliciesIdParameters)): QueryState<GetApprovalPoliciesIdData, GetApprovalPoliciesIdError> | undefined;
        /**
         * @summary Get an approval policy by ID
         * @description Retrieve a specific approval policy.
         */
        getInfiniteQueryState(parameters: GetApprovalPoliciesIdParameters | ServiceOperationInfiniteQueryKey<GetApprovalPoliciesIdSchema, GetApprovalPoliciesIdParameters>): QueryState<OperationInfiniteData<GetApprovalPoliciesIdData, GetApprovalPoliciesIdParameters>, GetApprovalPoliciesIdError> | undefined;
        /**
         * @summary Get an approval policy by ID
         * @description Retrieve a specific approval policy.
         */
        invalidateQueries<TInfinite extends boolean = false>(filters?: InvalidateQueryFilters<GetApprovalPoliciesIdSchema, GetApprovalPoliciesIdData, TInfinite, GetApprovalPoliciesIdParameters, GetApprovalPoliciesIdError>, options?: InvalidateOptions): Promise<void>;
        /**
         * @summary Get an approval policy by ID
         * @description Retrieve a specific approval policy.
         */
        isFetching<TInfinite extends boolean = false>(filters?: QueryFiltersByParameters<GetApprovalPoliciesIdSchema, GetApprovalPoliciesIdData, TInfinite, GetApprovalPoliciesIdParameters, GetApprovalPoliciesIdError> | QueryFiltersByQueryKey<GetApprovalPoliciesIdSchema, GetApprovalPoliciesIdData, TInfinite, GetApprovalPoliciesIdParameters, GetApprovalPoliciesIdError>): number;
        /**
         * @summary Get an approval policy by ID
         * @description Retrieve a specific approval policy.
         */
        <TMeta extends Record<string, any>, TSignal extends AbortSignal = AbortSignal>(options: QueryFnOptionsByQueryKey<GetApprovalPoliciesIdSchema, GetApprovalPoliciesIdParameters, TMeta, TSignal> | (QueryFnOptionsByParameters<GetApprovalPoliciesIdParameters, TMeta, TSignal>), client?: (schema: GetApprovalPoliciesIdSchema, options: {
            parameters: GetApprovalPoliciesIdParameters;
            signal?: TSignal;
            meta?: TMeta;
        }) => Promise<RequestFnResponse<GetApprovalPoliciesIdData, GetApprovalPoliciesIdError>>): Promise<RequestFnResponse<GetApprovalPoliciesIdData, GetApprovalPoliciesIdError>>;
        /**
         * @summary Get an approval policy by ID
         * @description Retrieve a specific approval policy.
         */
        refetchQueries<TInfinite extends boolean = false>(filters?: QueryFiltersByParameters<GetApprovalPoliciesIdSchema, GetApprovalPoliciesIdData, TInfinite, GetApprovalPoliciesIdParameters, GetApprovalPoliciesIdError> | QueryFiltersByQueryKey<GetApprovalPoliciesIdSchema, GetApprovalPoliciesIdData, TInfinite, GetApprovalPoliciesIdParameters, GetApprovalPoliciesIdError>, options?: RefetchOptions): Promise<void>;
        /**
         * @summary Get an approval policy by ID
         * @description Retrieve a specific approval policy.
         */
        removeQueries<TInfinite extends boolean = false>(filters?: QueryFiltersByParameters<GetApprovalPoliciesIdSchema, GetApprovalPoliciesIdData, TInfinite, GetApprovalPoliciesIdParameters, GetApprovalPoliciesIdError> | QueryFiltersByQueryKey<GetApprovalPoliciesIdSchema, GetApprovalPoliciesIdData, TInfinite, GetApprovalPoliciesIdParameters, GetApprovalPoliciesIdError>): void;
        /**
         * @summary Get an approval policy by ID
         * @description Retrieve a specific approval policy.
         */
        resetQueries<TInfinite extends boolean = false>(filters?: QueryFiltersByParameters<GetApprovalPoliciesIdSchema, GetApprovalPoliciesIdData, TInfinite, GetApprovalPoliciesIdParameters, GetApprovalPoliciesIdError> | QueryFiltersByQueryKey<GetApprovalPoliciesIdSchema, GetApprovalPoliciesIdData, TInfinite, GetApprovalPoliciesIdParameters, GetApprovalPoliciesIdError>, options?: ResetOptions): Promise<void>;
        /**
         * @summary Get an approval policy by ID
         * @description Retrieve a specific approval policy.
         */
        setInfiniteQueryData(parameters: GetApprovalPoliciesIdParameters | ServiceOperationInfiniteQueryKey<GetApprovalPoliciesIdSchema, GetApprovalPoliciesIdParameters>, updater: Updater<NoInfer<OperationInfiniteData<GetApprovalPoliciesIdData, GetApprovalPoliciesIdParameters>> | undefined, NoInfer<OperationInfiniteData<GetApprovalPoliciesIdData, GetApprovalPoliciesIdParameters>> | undefined>, options?: SetDataOptions): OperationInfiniteData<GetApprovalPoliciesIdData, GetApprovalPoliciesIdParameters> | undefined;
        /**
         * @summary Get an approval policy by ID
         * @description Retrieve a specific approval policy.
         */
        setQueriesData<TInfinite extends boolean = false>(filters: QueryFiltersByParameters<GetApprovalPoliciesIdSchema, GetApprovalPoliciesIdData, TInfinite, GetApprovalPoliciesIdParameters, GetApprovalPoliciesIdError> | QueryFiltersByQueryKey<GetApprovalPoliciesIdSchema, GetApprovalPoliciesIdData, TInfinite, GetApprovalPoliciesIdParameters, GetApprovalPoliciesIdError>, updater: Updater<NoInfer<GetApprovalPoliciesIdData> | undefined, NoInfer<GetApprovalPoliciesIdData> | undefined>, options?: SetDataOptions): Array<GetApprovalPoliciesIdData | undefined>;
        /**
         * @summary Get an approval policy by ID
         * @description Retrieve a specific approval policy.
         */
        setQueryData(parameters: (GetApprovalPoliciesIdParameters) | ServiceOperationQueryKey<GetApprovalPoliciesIdSchema, GetApprovalPoliciesIdParameters>, updater: Updater<NoInfer<GetApprovalPoliciesIdData> | undefined, NoInfer<GetApprovalPoliciesIdData> | undefined>, options?: SetDataOptions): GetApprovalPoliciesIdData | undefined;
        /**
         * @summary Get an approval policy by ID
         * @description Retrieve a specific approval policy.
         */
        getInfiniteQueryKey(parameters: GetApprovalPoliciesIdParameters): ServiceOperationInfiniteQueryKey<GetApprovalPoliciesIdSchema, GetApprovalPoliciesIdParameters>;
        /**
         * Performs asynchronous data fetching with support for infinite scrolling scenarios.
         * Manages paginated data and provides utilities for fetching additional pages.
         *
         * @see {@link https://openapi-qraft.github.io/openapi-qraft/docs/hooks/useInfiniteQuery|`useInfiniteQuery(...)` documentation}
         *
         * @example Infinite Query
         * ```ts
         * const { data, isLoading, fetchNextPage } = qraft.approvalPoliciesService.getApprovalPoliciesId.useInfiniteQuery({
         *     header: {
         *         "x-monite-version": "2023-06-04",
         *         "x-monite-entity-id": xMoniteEntityId
         *     },
         *     path: {
         *         approval_policy_id: approvalPolicyId
         *     }
         * }, {
         *     initialPageParam: {
         *         query: {
         *             items_order: initialItemsOrder
         *         }
         *     },
         *     getNextPageParam: (lastPage, allPages, lastPageParam, allPageParams) => getNextPageParams(lastPage)
         * })
         *
         * console.log(data);
         * fetchNextPage(); // Fetch the next page
         * ```
         */
        useInfiniteQuery<TPageParam extends GetApprovalPoliciesIdParameters, TQueryFnData = GetApprovalPoliciesIdData, TData = OperationInfiniteData<TQueryFnData, GetApprovalPoliciesIdParameters>>(parameters: ServiceOperationInfiniteQueryKey<GetApprovalPoliciesIdSchema, GetApprovalPoliciesIdParameters> | (GetApprovalPoliciesIdParameters), options: Omit<UndefinedInitialDataInfiniteOptions<TQueryFnData, GetApprovalPoliciesIdError, TData, ServiceOperationInfiniteQueryKey<GetApprovalPoliciesIdSchema, GetApprovalPoliciesIdParameters>, PartialParameters<TPageParam>>, "queryKey" | "getPreviousPageParam" | "getNextPageParam" | "initialPageParam"> & InfiniteQueryPageParamsOptions<TQueryFnData, PartialParameters<TPageParam>>): UseInfiniteQueryResult<TData, GetApprovalPoliciesIdError | Error>;
        /**
         * Performs asynchronous data fetching with support for infinite scrolling scenarios.
         * Manages paginated data and provides utilities for fetching additional pages.
         *
         * @see {@link https://openapi-qraft.github.io/openapi-qraft/docs/hooks/useInfiniteQuery|`useInfiniteQuery(...)` documentation}
         *
         * @example Infinite Query
         * ```ts
         * const { data, isLoading, fetchNextPage } = qraft.approvalPoliciesService.getApprovalPoliciesId.useInfiniteQuery({
         *     header: {
         *         "x-monite-version": "2023-06-04",
         *         "x-monite-entity-id": xMoniteEntityId
         *     },
         *     path: {
         *         approval_policy_id: approvalPolicyId
         *     }
         * }, {
         *     initialPageParam: {
         *         query: {
         *             items_order: initialItemsOrder
         *         }
         *     },
         *     getNextPageParam: (lastPage, allPages, lastPageParam, allPageParams) => getNextPageParams(lastPage)
         * })
         *
         * console.log(data);
         * fetchNextPage(); // Fetch the next page
         * ```
         */
        useInfiniteQuery<TPageParam extends GetApprovalPoliciesIdParameters, TQueryFnData = GetApprovalPoliciesIdData, TData = OperationInfiniteData<TQueryFnData, GetApprovalPoliciesIdParameters>>(parameters: ServiceOperationInfiniteQueryKey<GetApprovalPoliciesIdSchema, GetApprovalPoliciesIdParameters> | (GetApprovalPoliciesIdParameters), options: Omit<DefinedInitialDataInfiniteOptions<TQueryFnData, GetApprovalPoliciesIdError, TData, ServiceOperationInfiniteQueryKey<GetApprovalPoliciesIdSchema, GetApprovalPoliciesIdParameters>, PartialParameters<TPageParam>>, "queryKey" | "getPreviousPageParam" | "getNextPageParam" | "initialPageParam"> & InfiniteQueryPageParamsOptions<GetApprovalPoliciesIdData, PartialParameters<TPageParam>>): DefinedUseInfiniteQueryResult<TData, GetApprovalPoliciesIdError | Error>;
        /**
         * Monitors the number of queries currently fetching, matching the provided filters.
         * Useful for creating loading indicators or performing actions based on active requests.
         *
         * @see {@link https://openapi-qraft.github.io/openapi-qraft/docs/hooks/useIsFetching|`useIsFetching(...)` documentation}
         * @example Checks the total number of queries fetching from the specified service method,
         * both normal and infinite. If no parameters are provided, no filtering is applied.
         * ```ts
         * const getApprovalPoliciesIdTotal = qraft.approvalPoliciesService.getApprovalPoliciesId.useIsFetching()
         * ```
         * @example Checks the number of normal queries fetching with the specified parameters.
         * ```ts
         * const getApprovalPoliciesIdByParametersTotal = qraft.approvalPoliciesService.getApprovalPoliciesId.useIsFetching({
         *     infinite: false,
         *     parameters: {
         *         header: {
         *             "x-monite-version": "2023-06-04",
         *             "x-monite-entity-id": xMoniteEntityId
         *         },
         *         path: {
         *             approval_policy_id: approvalPolicyId
         *         },
         *         query: {
         *             items_order: itemsOrder
         *         }
         *     }
         * })
         * ```
         */
        useIsFetching<TInfinite extends boolean = false>(filters?: QueryFiltersByParameters<GetApprovalPoliciesIdSchema, GetApprovalPoliciesIdData, TInfinite, GetApprovalPoliciesIdParameters, GetApprovalPoliciesIdError> | QueryFiltersByQueryKey<GetApprovalPoliciesIdSchema, GetApprovalPoliciesIdData, TInfinite, GetApprovalPoliciesIdParameters, GetApprovalPoliciesIdError>): number;
        /**
         * Allows you to execute multiple asynchronous data fetching operations concurrently. This is especially useful for managing complex data dependencies in parallel.
         *
         * @summary Get an approval policy by ID
         * @description Retrieve a specific approval policy.
         * @see {@link https://openapi-qraft.github.io/openapi-qraft/docs/hooks/useQueries|`useQueries(...)` documentation}
         * @example Multiple queries. Returns `data`, `error`, `isSuccess` and other properties.
         * ```ts
         * const getApprovalPoliciesIdResults = qraft.approvalPoliciesService.getApprovalPoliciesId.useQueries({
         *     queries: [
         *         {
         *             header: {
         *                 "x-monite-version": "2023-06-04",
         *                 "x-monite-entity-id": xMoniteEntityId1
         *             },
         *             path: {
         *                 approval_policy_id: approvalPolicyId1
         *             },
         *             query: {
         *                 items_order: itemsOrder1
         *             }
         *         },
         *         {
         *             header: {
         *                 "x-monite-version": "2023-06-04",
         *                 "x-monite-entity-id": xMoniteEntityId2
         *             },
         *             path: {
         *                 approval_policy_id: approvalPolicyId2
         *             },
         *             query: {
         *                 items_order: itemsOrder2
         *             }
         *         }
         *     ]
         * });
         * getApprovalPoliciesIdResults.forEach(({ isSuccess, data, error }) => console.log({ isSuccess, data, error }));
         * ```
         * @example Combined results. Only the data will be returned.
         * ```ts
         * const getApprovalPoliciesIdCombinedResults = qraft.approvalPoliciesService.getApprovalPoliciesId.useQueries({
         *     combine: results => results.map(result => result.data),
         *     queries: [
         *         {
         *             header: {
         *                 "x-monite-version": "2023-06-04",
         *                 "x-monite-entity-id": xMoniteEntityId1
         *             },
         *             path: {
         *                 approval_policy_id: approvalPolicyId1
         *             },
         *             query: {
         *                 items_order: itemsOrder1
         *             }
         *         },
         *         {
         *             header: {
         *                 "x-monite-version": "2023-06-04",
         *                 "x-monite-entity-id": xMoniteEntityId2
         *             },
         *             path: {
         *                 approval_policy_id: approvalPolicyId2
         *             },
         *             query: {
         *                 items_order: itemsOrder2
         *             }
         *         }
         *     ]
         * });
         * getApprovalPoliciesIdCombinedResults.forEach(data => console.log({ data }));
         * ```
         */
        useQueries<T extends Array<UseQueryOptionsForUseQueries<GetApprovalPoliciesIdSchema, GetApprovalPoliciesIdParameters, GetApprovalPoliciesIdData, GetApprovalPoliciesIdError>>, TCombinedResult = Array<UseQueryResult<GetApprovalPoliciesIdData, GetApprovalPoliciesIdError>>>(options: {
            queries: T;
            combine?: (results: Array<UseQueryResult<GetApprovalPoliciesIdData, GetApprovalPoliciesIdError>>) => TCombinedResult;
        }): TCombinedResult;
        /**
         * @summary Get an approval policy by ID
         * @description Retrieve a specific approval policy.
         */
        getQueryKey(parameters: GetApprovalPoliciesIdParameters): ServiceOperationQueryKey<GetApprovalPoliciesIdSchema, GetApprovalPoliciesIdParameters>;
        /**
         * Performs asynchronous data fetching, manages loading states and error handling.
         *
         * @summary Get an approval policy by ID
         * @description Retrieve a specific approval policy.
         * @see {@link https://openapi-qraft.github.io/openapi-qraft/docs/hooks/useQuery|`useQuery(...)` documentation}
         * @example Query with parameters
         * ```ts
         * const { data, isLoading } = qraft.approvalPoliciesService.getApprovalPoliciesId.useQuery({
         *     header: {
         *         "x-monite-version": "2023-06-04",
         *         "x-monite-entity-id": xMoniteEntityId
         *     },
         *     path: {
         *         approval_policy_id: approvalPolicyId
         *     },
         *     query: {
         *         items_order: itemsOrder
         *     }
         * })
         * ```
         */
        useQuery<TData = GetApprovalPoliciesIdData>(parameters: ServiceOperationQueryKey<GetApprovalPoliciesIdSchema, GetApprovalPoliciesIdParameters> | (GetApprovalPoliciesIdParameters), options?: Omit<UndefinedInitialDataOptions<GetApprovalPoliciesIdData, GetApprovalPoliciesIdError, TData, ServiceOperationQueryKey<GetApprovalPoliciesIdSchema, GetApprovalPoliciesIdParameters>>, "queryKey">): UseQueryResult<TData, GetApprovalPoliciesIdError | Error>;
        /**
         * Performs asynchronous data fetching, manages loading states and error handling.
         *
         * @summary Get an approval policy by ID
         * @description Retrieve a specific approval policy.
         * @see {@link https://openapi-qraft.github.io/openapi-qraft/docs/hooks/useQuery|`useQuery(...)` documentation}
         * @example Query with parameters
         * ```ts
         * const { data, isLoading } = qraft.approvalPoliciesService.getApprovalPoliciesId.useQuery({
         *     header: {
         *         "x-monite-version": "2023-06-04",
         *         "x-monite-entity-id": xMoniteEntityId
         *     },
         *     path: {
         *         approval_policy_id: approvalPolicyId
         *     },
         *     query: {
         *         items_order: itemsOrder
         *     }
         * })
         * ```
         */
        useQuery<TData = GetApprovalPoliciesIdData>(parameters: ServiceOperationQueryKey<GetApprovalPoliciesIdSchema, GetApprovalPoliciesIdParameters> | (GetApprovalPoliciesIdParameters), options: Omit<DefinedInitialDataOptions<GetApprovalPoliciesIdData, GetApprovalPoliciesIdError, TData, ServiceOperationQueryKey<GetApprovalPoliciesIdSchema, GetApprovalPoliciesIdParameters>>, "queryKey">): DefinedUseQueryResult<TData, GetApprovalPoliciesIdError | Error>;
        /**
         * Performs asynchronous data fetching with support for infinite scrolling scenarios.
         * Manages paginated data and provides utilities for fetching additional pages.
         * It functions similarly to `useInfiniteQuery`, but with added support for React Suspense.
         *
         * @see {@link https://openapi-qraft.github.io/openapi-qraft/docs/hooks/useSuspenseInfiniteQuery|`useSuspenseInfiniteQuery(...)` documentation}
         *
         * @example Suspense Infinite Query
         * ```ts
         * const { data, isLoading, fetchNextPage } = qraft.approvalPoliciesService.getApprovalPoliciesId.useSuspenseInfiniteQuery({
         *     header: {
         *         "x-monite-version": "2023-06-04",
         *         "x-monite-entity-id": xMoniteEntityId
         *     },
         *     path: {
         *         approval_policy_id: approvalPolicyId
         *     }
         * }, {
         *     initialPageParam: {
         *         query: {
         *             items_order: initialItemsOrder
         *         }
         *     },
         *     getNextPageParam: (lastPage, allPages, lastPageParam, allPageParams) => getNextPageParams(lastPage)
         * })
         *
         * console.log(data);
         * fetchNextPage(); // Fetch the next page
         * ```
         */
        useSuspenseInfiniteQuery<TPageParam extends GetApprovalPoliciesIdParameters, TData = GetApprovalPoliciesIdData>(parameters: ServiceOperationInfiniteQueryKey<GetApprovalPoliciesIdSchema, GetApprovalPoliciesIdParameters> | (GetApprovalPoliciesIdParameters), options: Omit<UseSuspenseInfiniteQueryOptions<GetApprovalPoliciesIdData, GetApprovalPoliciesIdError, OperationInfiniteData<TData, GetApprovalPoliciesIdParameters>, GetApprovalPoliciesIdData, ServiceOperationInfiniteQueryKey<GetApprovalPoliciesIdSchema, GetApprovalPoliciesIdParameters>, PartialParameters<TPageParam>>, "queryKey" | "getPreviousPageParam" | "getNextPageParam" | "initialPageParam"> & InfiniteQueryPageParamsOptions<GetApprovalPoliciesIdData, PartialParameters<TPageParam>>): UseSuspenseInfiniteQueryResult<OperationInfiniteData<TData, GetApprovalPoliciesIdParameters>, GetApprovalPoliciesIdError | Error>;
        /**
         * @summary Get an approval policy by ID
         * @description Retrieve a specific approval policy.
         */
        useSuspenseQueries<T extends Array<UseQueryOptionsForUseSuspenseQuery<GetApprovalPoliciesIdSchema, GetApprovalPoliciesIdParameters, GetApprovalPoliciesIdData, GetApprovalPoliciesIdError>>, TCombinedResult = Array<UseSuspenseQueryResult<GetApprovalPoliciesIdData, GetApprovalPoliciesIdError>>>(options: {
            queries: T;
            combine?: (results: Array<WithOptional<UseSuspenseQueryResult<GetApprovalPoliciesIdData, GetApprovalPoliciesIdError>, "data">>) => TCombinedResult;
        }): TCombinedResult;
        /**
         * Performs asynchronous data fetching with Suspense support.
         * Similar to useQuery but integrates with React Suspense for loading states.
         *
         * @summary Get an approval policy by ID
         * @description Retrieve a specific approval policy.
         * @see {@link https://openapi-qraft.github.io/openapi-qraft/docs/hooks/useSuspenseQuery|`useSuspenseQuery(...)` documentation}
         * @example Suspense Query with parameters
         * ```ts
         * const data = qraft.approvalPoliciesService.getApprovalPoliciesId.useSuspenseQuery({
         *     header: {
         *         "x-monite-version": "2023-06-04",
         *         "x-monite-entity-id": xMoniteEntityId
         *     },
         *     path: {
         *         approval_policy_id: approvalPolicyId
         *     },
         *     query: {
         *         items_order: itemsOrder
         *     }
         * })
         * ```
         */
        useSuspenseQuery<TData = GetApprovalPoliciesIdData>(parameters: ServiceOperationQueryKey<GetApprovalPoliciesIdSchema, GetApprovalPoliciesIdParameters> | (GetApprovalPoliciesIdParameters), options?: Omit<UseSuspenseQueryOptions<GetApprovalPoliciesIdData, GetApprovalPoliciesIdError, TData, ServiceOperationQueryKey<GetApprovalPoliciesIdSchema, GetApprovalPoliciesIdParameters>>, "queryKey">): UseSuspenseQueryResult<TData, GetApprovalPoliciesIdError | Error>;
        schema: GetApprovalPoliciesIdSchema;
        types: {
            parameters: GetApprovalPoliciesIdParameters;
            data: GetApprovalPoliciesIdData;
            error: GetApprovalPoliciesIdError;
        };
    };
    /**
     * @summary Delete an approval policy
     * @description Delete an existing approval policy.
     */
    deleteApprovalPoliciesId: {
        /**
         * @summary Delete an approval policy
         * @description Delete an existing approval policy.
         */
        getMutationKey(parameters: DeleteApprovalPoliciesIdParameters | void): ServiceOperationMutationKey<DeleteApprovalPoliciesIdSchema, DeleteApprovalPoliciesIdParameters>;
        /**
         * Enables performing asynchronous data mutation operations such as POST, PUT, PATCH, or DELETE requests.
         * Handles loading state, optimistic updates, and error handling.
         *
         * @see {@link https://openapi-qraft.github.io/openapi-qraft/docs/hooks/useMutation|`useMutation(...)` documentation}
         * @example Mutation with predefined parameters, e.g., for updating
         * ```ts
         * const { mutate, isPending } = qraft.approvalPoliciesService.deleteApprovalPoliciesId.useMutation({
         *     header: {
         *         "x-monite-version": "2023-06-04",
         *         "x-monite-entity-id": xMoniteEntityId
         *     },
         *     path: {
         *         approval_policy_id: approvalPolicyId
         *     },
         *     query: {
         *         limit: limit
         *     }
         * })
         * mutate(body);
         * ```
         * @example Mutation without predefined parameters, e.g., for creating
         * ```ts
         * const { mutate, isPending } = qraft.approvalPoliciesService.deleteApprovalPoliciesId.useMutation()
         * mutate({
         *     body: bodyPayload,
         *     header: {
         *         "x-monite-version": "2023-06-04",
         *         "x-monite-entity-id": xMoniteEntityId
         *     },
         *     path: {
         *         approval_policy_id: approvalPolicyId
         *     },
         *     query: {
         *         limit: limit
         *     }
         * });
         * ```
         */
        useMutation<TVariables extends DeleteApprovalPoliciesIdBody, TContext = unknown>(parameters: DeleteApprovalPoliciesIdParameters, options?: ServiceOperationUseMutationOptions<DeleteApprovalPoliciesIdSchema, DeleteApprovalPoliciesIdData, DeleteApprovalPoliciesIdParameters, TVariables, DeleteApprovalPoliciesIdError | Error, TContext>): UseMutationResult<DeleteApprovalPoliciesIdData, DeleteApprovalPoliciesIdError | Error, AreAllOptional<TVariables> extends true ? TVariables | void : TVariables, TContext>;
        /**
         * Enables performing asynchronous data mutation operations such as POST, PUT, PATCH, or DELETE requests.
         * Handles loading state, optimistic updates, and error handling.
         *
         * @see {@link https://openapi-qraft.github.io/openapi-qraft/docs/hooks/useMutation|`useMutation(...)` documentation}
         * @example Mutation with predefined parameters, e.g., for updating
         * ```ts
         * const { mutate, isPending } = qraft.approvalPoliciesService.deleteApprovalPoliciesId.useMutation({
         *     header: {
         *         "x-monite-version": "2023-06-04",
         *         "x-monite-entity-id": xMoniteEntityId
         *     },
         *     path: {
         *         approval_policy_id: approvalPolicyId
         *     },
         *     query: {
         *         limit: limit
         *     }
         * })
         * mutate(body);
         * ```
         * @example Mutation without predefined parameters, e.g., for creating
         * ```ts
         * const { mutate, isPending } = qraft.approvalPoliciesService.deleteApprovalPoliciesId.useMutation()
         * mutate({
         *     body: bodyPayload,
         *     header: {
         *         "x-monite-version": "2023-06-04",
         *         "x-monite-entity-id": xMoniteEntityId
         *     },
         *     path: {
         *         approval_policy_id: approvalPolicyId
         *     },
         *     query: {
         *         limit: limit
         *     }
         * });
         * ```
         */
        useMutation<TVariables extends MutationVariables<DeleteApprovalPoliciesIdBody, DeleteApprovalPoliciesIdParameters>, TContext = unknown>(parameters: void, options?: ServiceOperationUseMutationOptions<DeleteApprovalPoliciesIdSchema, DeleteApprovalPoliciesIdData, DeleteApprovalPoliciesIdParameters, TVariables, DeleteApprovalPoliciesIdError | Error, TContext>): UseMutationResult<DeleteApprovalPoliciesIdData, DeleteApprovalPoliciesIdError | Error, TVariables, TContext>;
        /**
         * Returns the count of currently in-progress mutations.
         *
         * @summary Delete an approval policy
         * @description Delete an existing approval policy.
         * @see {@link https://openapi-qraft.github.io/openapi-qraft/docs/hooks/useIsMutating|`useIsMutating(...)` documentation}
         * @example Check how many mutations are currently in progress for the specified service method.
         * ```ts
         * const deleteApprovalPoliciesIdTotal = qraft.approvalPoliciesService.deleteApprovalPoliciesId.useIsMutating()
         * ```
         * @example Check how many mutations are currently in progress with the specified parameters.
         * ```ts
         * const deleteApprovalPoliciesIdTotal = qraft.approvalPoliciesService.deleteApprovalPoliciesId.useIsMutating({
         *     parameters: {
         *         header: {
         *             "x-monite-version": "2023-06-04",
         *             "x-monite-entity-id": xMoniteEntityId
         *         },
         *         path: {
         *             approval_policy_id: approvalPolicyId
         *         },
         *         query: {
         *             limit: limit
         *         }
         *     }
         * })
         * ```
         */
        useIsMutating<TContext = unknown>(filters?: MutationFiltersByParameters<DeleteApprovalPoliciesIdBody, DeleteApprovalPoliciesIdData, DeleteApprovalPoliciesIdParameters, DeleteApprovalPoliciesIdError | Error, TContext> | MutationFiltersByMutationKey<DeleteApprovalPoliciesIdSchema, DeleteApprovalPoliciesIdBody, DeleteApprovalPoliciesIdData, DeleteApprovalPoliciesIdParameters, DeleteApprovalPoliciesIdError | Error, TContext>): number;
        /**
         * @summary Delete an approval policy
         * @description Delete an existing approval policy.
         */
        isMutating<TContext>(filters?: MutationFiltersByParameters<DeleteApprovalPoliciesIdBody, DeleteApprovalPoliciesIdData, DeleteApprovalPoliciesIdParameters, DeleteApprovalPoliciesIdError | Error, TContext> | MutationFiltersByMutationKey<DeleteApprovalPoliciesIdSchema, DeleteApprovalPoliciesIdBody, DeleteApprovalPoliciesIdData, DeleteApprovalPoliciesIdParameters, DeleteApprovalPoliciesIdError | Error, TContext>): number;
        /**
         * @summary Delete an approval policy
         * @description Delete an existing approval policy.
         */
        (options: ServiceOperationMutationFnOptions<DeleteApprovalPoliciesIdBody, DeleteApprovalPoliciesIdParameters>, client?: (schema: DeleteApprovalPoliciesIdSchema, options: ServiceOperationMutationFnOptions<DeleteApprovalPoliciesIdBody, DeleteApprovalPoliciesIdParameters>) => Promise<RequestFnResponse<DeleteApprovalPoliciesIdData, DeleteApprovalPoliciesIdError>>): Promise<RequestFnResponse<DeleteApprovalPoliciesIdData, DeleteApprovalPoliciesIdError>>;
        /**
         * Provides access to the current state of a mutation, including its status, any resulting data, and associated errors.
         *
         * @summary Delete an approval policy
         * @description Delete an existing approval policy.
         * @see {@link https://openapi-qraft.github.io/openapi-qraft/docs/hooks/useMutationState|`useMutationState(...)` documentation}
         * @example Get all variables of all running mutations.
         * ```ts
         * const deleteApprovalPoliciesIdPendingMutationVariables = qraft.approvalPoliciesService.deleteApprovalPoliciesId.useMutationState({
         *     filters: {
         *         status: "pending"
         *     },
         *     select: mutation => mutation.state.variables
         * })
         * ```
         * @example Get all data for specific mutations via the `parameters`.
         * ```ts
         * const deleteApprovalPoliciesIdMutationData = qraft.approvalPoliciesService.deleteApprovalPoliciesId.useMutationState({
         *     filters: {
         *         parameters: {
         *             header: {
         *                 "x-monite-version": "2023-06-04",
         *                 "x-monite-entity-id": xMoniteEntityId
         *             },
         *             path: {
         *                 approval_policy_id: approvalPolicyId
         *             },
         *             query: {
         *                 limit: limit
         *             }
         *         }
         *     },
         *     select: mutation => mutation.state.data
         * })
         * ```
         */
        useMutationState<TContext = unknown, TResult = MutationState<DeleteApprovalPoliciesIdData, DeleteApprovalPoliciesIdError | Error, MutationVariables<DeleteApprovalPoliciesIdBody, DeleteApprovalPoliciesIdParameters>, TContext>>(options?: {
            filters?: MutationFiltersByParameters<DeleteApprovalPoliciesIdBody, DeleteApprovalPoliciesIdData, DeleteApprovalPoliciesIdParameters, DeleteApprovalPoliciesIdError | Error, TContext> | MutationFiltersByMutationKey<DeleteApprovalPoliciesIdSchema, DeleteApprovalPoliciesIdBody, DeleteApprovalPoliciesIdData, DeleteApprovalPoliciesIdParameters, DeleteApprovalPoliciesIdError | Error, TContext>;
            select?: (mutation: Mutation<DeleteApprovalPoliciesIdData, DeleteApprovalPoliciesIdError | Error, MutationVariables<DeleteApprovalPoliciesIdBody, DeleteApprovalPoliciesIdParameters>, TContext>) => TResult;
        }): Array<TResult>;
        schema: DeleteApprovalPoliciesIdSchema;
        types: {
            parameters: DeleteApprovalPoliciesIdParameters;
            data: DeleteApprovalPoliciesIdData;
            error: DeleteApprovalPoliciesIdError;
            body: DeleteApprovalPoliciesIdBody;
        };
    };
    /**
     * @summary Update an approval policy
     * @description Update an existing approval policy.
     */
    patchApprovalPoliciesId: {
        /**
         * @summary Update an approval policy
         * @description Update an existing approval policy.
         */
        getMutationKey(parameters: PatchApprovalPoliciesIdParameters | void): ServiceOperationMutationKey<PatchApprovalPoliciesIdSchema, PatchApprovalPoliciesIdParameters>;
        /**
         * Enables performing asynchronous data mutation operations such as POST, PUT, PATCH, or DELETE requests.
         * Handles loading state, optimistic updates, and error handling.
         *
         * @see {@link https://openapi-qraft.github.io/openapi-qraft/docs/hooks/useMutation|`useMutation(...)` documentation}
         * @example Mutation with predefined parameters, e.g., for updating
         * ```ts
         * const { mutate, isPending } = qraft.approvalPoliciesService.patchApprovalPoliciesId.useMutation({
         *     header: {
         *         "x-monite-version": "2023-06-04",
         *         "x-monite-entity-id": xMoniteEntityId
         *     },
         *     path: {
         *         approval_policy_id: approvalPolicyId
         *     },
         *     query: {
         *         limit: limit
         *     }
         * })
         * mutate(body);
         * ```
         * @example Mutation without predefined parameters, e.g., for creating
         * ```ts
         * const { mutate, isPending } = qraft.approvalPoliciesService.patchApprovalPoliciesId.useMutation()
         * mutate({
         *     body: bodyPayload,
         *     header: {
         *         "x-monite-version": "2023-06-04",
         *         "x-monite-entity-id": xMoniteEntityId
         *     },
         *     path: {
         *         approval_policy_id: approvalPolicyId
         *     },
         *     query: {
         *         limit: limit
         *     }
         * });
         * ```
         */
        useMutation<TVariables extends PatchApprovalPoliciesIdBody, TContext = unknown>(parameters: PatchApprovalPoliciesIdParameters, options?: ServiceOperationUseMutationOptions<PatchApprovalPoliciesIdSchema, PatchApprovalPoliciesIdData, PatchApprovalPoliciesIdParameters, TVariables, PatchApprovalPoliciesIdError | Error, TContext>): UseMutationResult<PatchApprovalPoliciesIdData, PatchApprovalPoliciesIdError | Error, AreAllOptional<TVariables> extends true ? TVariables | void : TVariables, TContext>;
        /**
         * Enables performing asynchronous data mutation operations such as POST, PUT, PATCH, or DELETE requests.
         * Handles loading state, optimistic updates, and error handling.
         *
         * @see {@link https://openapi-qraft.github.io/openapi-qraft/docs/hooks/useMutation|`useMutation(...)` documentation}
         * @example Mutation with predefined parameters, e.g., for updating
         * ```ts
         * const { mutate, isPending } = qraft.approvalPoliciesService.patchApprovalPoliciesId.useMutation({
         *     header: {
         *         "x-monite-version": "2023-06-04",
         *         "x-monite-entity-id": xMoniteEntityId
         *     },
         *     path: {
         *         approval_policy_id: approvalPolicyId
         *     },
         *     query: {
         *         limit: limit
         *     }
         * })
         * mutate(body);
         * ```
         * @example Mutation without predefined parameters, e.g., for creating
         * ```ts
         * const { mutate, isPending } = qraft.approvalPoliciesService.patchApprovalPoliciesId.useMutation()
         * mutate({
         *     body: bodyPayload,
         *     header: {
         *         "x-monite-version": "2023-06-04",
         *         "x-monite-entity-id": xMoniteEntityId
         *     },
         *     path: {
         *         approval_policy_id: approvalPolicyId
         *     },
         *     query: {
         *         limit: limit
         *     }
         * });
         * ```
         */
        useMutation<TVariables extends MutationVariables<PatchApprovalPoliciesIdBody, PatchApprovalPoliciesIdParameters>, TContext = unknown>(parameters: void, options?: ServiceOperationUseMutationOptions<PatchApprovalPoliciesIdSchema, PatchApprovalPoliciesIdData, PatchApprovalPoliciesIdParameters, TVariables, PatchApprovalPoliciesIdError | Error, TContext>): UseMutationResult<PatchApprovalPoliciesIdData, PatchApprovalPoliciesIdError | Error, TVariables, TContext>;
        /**
         * Returns the count of currently in-progress mutations.
         *
         * @summary Update an approval policy
         * @description Update an existing approval policy.
         * @see {@link https://openapi-qraft.github.io/openapi-qraft/docs/hooks/useIsMutating|`useIsMutating(...)` documentation}
         * @example Check how many mutations are currently in progress for the specified service method.
         * ```ts
         * const patchApprovalPoliciesIdTotal = qraft.approvalPoliciesService.patchApprovalPoliciesId.useIsMutating()
         * ```
         * @example Check how many mutations are currently in progress with the specified parameters.
         * ```ts
         * const patchApprovalPoliciesIdTotal = qraft.approvalPoliciesService.patchApprovalPoliciesId.useIsMutating({
         *     parameters: {
         *         header: {
         *             "x-monite-version": "2023-06-04",
         *             "x-monite-entity-id": xMoniteEntityId
         *         },
         *         path: {
         *             approval_policy_id: approvalPolicyId
         *         },
         *         query: {
         *             limit: limit
         *         }
         *     }
         * })
         * ```
         */
        useIsMutating<TContext = unknown>(filters?: MutationFiltersByParameters<PatchApprovalPoliciesIdBody, PatchApprovalPoliciesIdData, PatchApprovalPoliciesIdParameters, PatchApprovalPoliciesIdError | Error, TContext> | MutationFiltersByMutationKey<PatchApprovalPoliciesIdSchema, PatchApprovalPoliciesIdBody, PatchApprovalPoliciesIdData, PatchApprovalPoliciesIdParameters, PatchApprovalPoliciesIdError | Error, TContext>): number;
        /**
         * @summary Update an approval policy
         * @description Update an existing approval policy.
         */
        isMutating<TContext>(filters?: MutationFiltersByParameters<PatchApprovalPoliciesIdBody, PatchApprovalPoliciesIdData, PatchApprovalPoliciesIdParameters, PatchApprovalPoliciesIdError | Error, TContext> | MutationFiltersByMutationKey<PatchApprovalPoliciesIdSchema, PatchApprovalPoliciesIdBody, PatchApprovalPoliciesIdData, PatchApprovalPoliciesIdParameters, PatchApprovalPoliciesIdError | Error, TContext>): number;
        /**
         * @summary Update an approval policy
         * @description Update an existing approval policy.
         */
        (options: ServiceOperationMutationFnOptions<PatchApprovalPoliciesIdBody, PatchApprovalPoliciesIdParameters>, client?: (schema: PatchApprovalPoliciesIdSchema, options: ServiceOperationMutationFnOptions<PatchApprovalPoliciesIdBody, PatchApprovalPoliciesIdParameters>) => Promise<RequestFnResponse<PatchApprovalPoliciesIdData, PatchApprovalPoliciesIdError>>): Promise<RequestFnResponse<PatchApprovalPoliciesIdData, PatchApprovalPoliciesIdError>>;
        /**
         * Provides access to the current state of a mutation, including its status, any resulting data, and associated errors.
         *
         * @summary Update an approval policy
         * @description Update an existing approval policy.
         * @see {@link https://openapi-qraft.github.io/openapi-qraft/docs/hooks/useMutationState|`useMutationState(...)` documentation}
         * @example Get all variables of all running mutations.
         * ```ts
         * const patchApprovalPoliciesIdPendingMutationVariables = qraft.approvalPoliciesService.patchApprovalPoliciesId.useMutationState({
         *     filters: {
         *         status: "pending"
         *     },
         *     select: mutation => mutation.state.variables
         * })
         * ```
         * @example Get all data for specific mutations via the `parameters`.
         * ```ts
         * const patchApprovalPoliciesIdMutationData = qraft.approvalPoliciesService.patchApprovalPoliciesId.useMutationState({
         *     filters: {
         *         parameters: {
         *             header: {
         *                 "x-monite-version": "2023-06-04",
         *                 "x-monite-entity-id": xMoniteEntityId
         *             },
         *             path: {
         *                 approval_policy_id: approvalPolicyId
         *             },
         *             query: {
         *                 limit: limit
         *             }
         *         }
         *     },
         *     select: mutation => mutation.state.data
         * })
         * ```
         */
        useMutationState<TContext = unknown, TResult = MutationState<PatchApprovalPoliciesIdData, PatchApprovalPoliciesIdError | Error, MutationVariables<PatchApprovalPoliciesIdBody, PatchApprovalPoliciesIdParameters>, TContext>>(options?: {
            filters?: MutationFiltersByParameters<PatchApprovalPoliciesIdBody, PatchApprovalPoliciesIdData, PatchApprovalPoliciesIdParameters, PatchApprovalPoliciesIdError | Error, TContext> | MutationFiltersByMutationKey<PatchApprovalPoliciesIdSchema, PatchApprovalPoliciesIdBody, PatchApprovalPoliciesIdData, PatchApprovalPoliciesIdParameters, PatchApprovalPoliciesIdError | Error, TContext>;
            select?: (mutation: Mutation<PatchApprovalPoliciesIdData, PatchApprovalPoliciesIdError | Error, MutationVariables<PatchApprovalPoliciesIdBody, PatchApprovalPoliciesIdParameters>, TContext>) => TResult;
        }): Array<TResult>;
        schema: PatchApprovalPoliciesIdSchema;
        types: {
            parameters: PatchApprovalPoliciesIdParameters;
            data: PatchApprovalPoliciesIdData;
            error: PatchApprovalPoliciesIdError;
            body: PatchApprovalPoliciesIdBody;
        };
    };
}
export const approvalPoliciesService: {
    /**
     * @summary Get an approval policy by ID
     * @description Retrieve a specific approval policy.
     */
    getApprovalPoliciesId: {
        schema: {
            method: "get";
            url: "/approval_policies/{approval_policy_id}";
            security: [
                "partnerToken"
            ];
        };
    };
    /**
     * @summary Delete an approval policy
     * @description Delete an existing approval policy.
     */
    deleteApprovalPoliciesId: {
        schema: {
            method: "delete";
            url: "/approval_policies/{approval_policy_id}";
            security: [
                "HTTPBearer"
            ];
        };
    };
    /**
     * @summary Update an approval policy
     * @description Update an existing approval policy.
     */
    patchApprovalPoliciesId: {
        schema: {
            method: "patch";
            url: "/approval_policies/{approval_policy_id}";
            mediaType: [
                "application/json"
            ];
            security: [
                "HTTPBearer"
            ];
        };
    };
} = {
    getApprovalPoliciesId: {
        schema: {
            method: "get",
            url: "/approval_policies/{approval_policy_id}",
            security: ["partnerToken"]
        }
    },
    deleteApprovalPoliciesId: {
        schema: {
            method: "delete",
            url: "/approval_policies/{approval_policy_id}",
            security: ["HTTPBearer"]
        }
    },
    patchApprovalPoliciesId: {
        schema: {
            method: "patch",
            url: "/approval_policies/{approval_policy_id}",
            mediaType: ["application/json"],
            security: ["HTTPBearer"]
        }
    }
};
type GetApprovalPoliciesIdSchema = {
    method: "get";
    url: "/approval_policies/{approval_policy_id}";
    security: [
        "partnerToken"
    ];
};
type GetApprovalPoliciesIdParameters = paths["/approval_policies/{approval_policy_id}"]["get"]["parameters"];
type GetApprovalPoliciesIdData = paths["/approval_policies/{approval_policy_id}"]["get"]["responses"]["200"]["content"]["application/json"];
type GetApprovalPoliciesIdError = paths["/approval_policies/{approval_policy_id}"]["get"]["responses"]["401"]["content"]["application/json"] | paths["/approval_policies/{approval_policy_id}"]["get"]["responses"]["422"]["content"]["application/json"] | paths["/approval_policies/{approval_policy_id}"]["get"]["responses"]["default"]["content"]["application/json"];
type DeleteApprovalPoliciesIdSchema = {
    method: "delete";
    url: "/approval_policies/{approval_policy_id}";
    security: [
        "HTTPBearer"
    ];
};
type DeleteApprovalPoliciesIdParameters = paths["/approval_policies/{approval_policy_id}"]["delete"]["parameters"];
type DeleteApprovalPoliciesIdData = paths["/approval_policies/{approval_policy_id}"]["delete"]["responses"]["200"]["content"]["application/json"];
type DeleteApprovalPoliciesIdError = paths["/approval_policies/{approval_policy_id}"]["delete"]["responses"]["401"]["content"]["application/json"] | paths["/approval_policies/{approval_policy_id}"]["delete"]["responses"]["422"]["content"]["application/json"] | paths["/approval_policies/{approval_policy_id}"]["delete"]["responses"]["default"]["content"]["application/json"];
type DeleteApprovalPoliciesIdBody = undefined;
type PatchApprovalPoliciesIdSchema = {
    method: "patch";
    url: "/approval_policies/{approval_policy_id}";
    mediaType: [
        "application/json"
    ];
    security: [
        "HTTPBearer"
    ];
};
type PatchApprovalPoliciesIdParameters = paths["/approval_policies/{approval_policy_id}"]["patch"]["parameters"];
type PatchApprovalPoliciesIdData = paths["/approval_policies/{approval_policy_id}"]["patch"]["responses"]["200"]["content"]["application/json"];
type PatchApprovalPoliciesIdError = paths["/approval_policies/{approval_policy_id}"]["patch"]["responses"]["401"]["content"]["application/json"] | paths["/approval_policies/{approval_policy_id}"]["patch"]["responses"]["422"]["content"]["application/json"] | paths["/approval_policies/{approval_policy_id}"]["patch"]["responses"]["default"]["content"]["application/json"];
type PatchApprovalPoliciesIdBody = NonNullable<paths["/approval_policies/{approval_policy_id}"]["patch"]["requestBody"]>["content"]["application/json"];
