/**
 * This file was auto-generated by @openapi-qraft/cli.
 * Do not make direct changes to the file.
 */

import type { paths } from "../../openapi.js";
import type { ServiceOperationQuery, ServiceOperationMutation } from "@openapi-qraft/react";
export interface FilesService {
    /** @summary Get a files by ID */
    getFiles: ServiceOperationQuery<{
        method: "get";
        url: "/files";
        security: [
            "HTTPBearer"
        ];
    }, paths["/files"]["get"]["responses"]["200"]["content"]["application/json"], paths["/files"]["get"]["parameters"], paths["/files"]["get"]["responses"]["405"]["content"]["application/json"] | paths["/files"]["get"]["responses"]["422"]["content"]["application/json"] | paths["/files"]["get"]["responses"]["default"]["content"]["application/json"]>;
    /** @summary Upload a files by ID */
    postFiles: ServiceOperationMutation<{
        method: "post";
        url: "/files";
        mediaType: "multipart/form-data";
    }, NonNullable<paths["/files"]["post"]["requestBody"]>["content"]["multipart/form-data"], paths["/files"]["post"]["responses"]["200"]["content"]["application/json"], undefined, paths["/files"]["post"]["responses"]["default"]["content"]["application/json"]>;
    /** @summary Delete all files */
    deleteFiles: ServiceOperationMutation<{
        method: "delete";
        url: "/files";
    }, undefined, paths["/files"]["delete"]["responses"]["200"]["content"]["application/json"], paths["/files"]["delete"]["parameters"], paths["/files"]["delete"]["responses"]["default"]["content"]["application/json"]>;
    /**
     * @deprecated
     * @summary Get a file list
     */
    getFileList: ServiceOperationQuery<{
        method: "get";
        url: "/files/list";
        security: [
            "HTTPBearer"
        ];
    }, paths["/files/list"]["get"]["responses"]["200"]["content"]["application/json"], paths["/files/list"]["get"]["parameters"], paths["/files/list"]["get"]["responses"]["default"]["content"]["application/json"]>;
}
export const filesService: {
    /** @summary Get a files by ID */
    getFiles: {
        schema: {
            method: "get";
            url: "/files";
            security: [
                "HTTPBearer"
            ];
        };
    };
    /** @summary Upload a files by ID */
    postFiles: {
        schema: {
            method: "post";
            url: "/files";
            mediaType: "multipart/form-data";
        };
    };
    /** @summary Delete all files */
    deleteFiles: {
        schema: {
            method: "delete";
            url: "/files";
        };
    };
    /**
     * @deprecated
     * @summary Get a file list
     */
    getFileList: {
        schema: {
            method: "get";
            url: "/files/list";
            security: [
                "HTTPBearer"
            ];
        };
    };
} = {
    getFiles: {
        schema: {
            method: "get",
            url: "/files",
            security: ["HTTPBearer"]
        }
    },
    postFiles: {
        schema: {
            method: "post",
            url: "/files",
            mediaType: "multipart/form-data"
        }
    },
    deleteFiles: {
        schema: {
            method: "delete",
            url: "/files"
        }
    },
    getFileList: {
        schema: {
            method: "get",
            url: "/files/list",
            security: ["HTTPBearer"]
        }
    }
};
