/**
 * This file was auto-generated by @openapi-qraft/cli.
 * Do not make direct changes to the file.
 */

import type { APIBasicClientMethodsServices, APIBasicQueryClientMethodsServices, APIQueryClientHooksServices, APIQueryClientMethodsServices, CreateAPIBasicClientOptions, CreateAPIBasicQueryClientOptions, CreateAPIClientOptions, CreateAPIQueryClientOptions, UnionServiceOperationsDeclaration } from "@openapi-qraft/react";
import { APIClientContext } from "./APIClientContext";
import type * as allCallbacks from "@openapi-qraft/react/callbacks/index";
import { qraftReactAPIClient } from "@openapi-qraft/react";
const defaultCallbacks = {} as const;
export function createAPIClient<Services extends UnionServiceOperationsDeclaration<Services>>(services: Services, options: CreateAPIQueryClientOptions, callbacks: AllCallbacks): APIQueryClientMethodsServices<Services, AllCallbacks>;
export function createAPIClient<Services extends UnionServiceOperationsDeclaration<Services>, Callbacks extends Partial<AllCallbacks> = DefaultCallbacks>(services: Services, options: CreateAPIQueryClientOptions, callbacks: Callbacks): APIQueryClientMethodsServices<Services, Callbacks>;
export function createAPIClient<Services extends UnionServiceOperationsDeclaration<Services>, Callbacks extends Partial<AllCallbacks> = DefaultCallbacks>(services: Services, options: CreateAPIBasicQueryClientOptions, callbacks: Callbacks): APIBasicQueryClientMethodsServices<Services, Callbacks>;
export function createAPIClient<Services extends UnionServiceOperationsDeclaration<Services>, Callbacks extends Partial<AllCallbacks> = DefaultCallbacks>(services: Services, options: CreateAPIBasicClientOptions, callbacks: Callbacks): APIBasicClientMethodsServices<Services, Callbacks>;
export function createAPIClient<Services extends UnionServiceOperationsDeclaration<Services>, Callbacks extends Partial<AllCallbacks> = DefaultCallbacks>(services: Services, callbacks: Callbacks): APIQueryClientHooksServices<Services, Callbacks>;
export function createAPIClient<Services extends UnionServiceOperationsDeclaration<Services>, Callbacks extends Partial<AllCallbacks> = DefaultCallbacks>(services: Services, callbacksOrOptions: CreateAPIClientOptions | Callbacks, callbacks: Callbacks = defaultCallbacks as Callbacks): APIQueryClientMethodsServices<Services, AllCallbacks> | APIQueryClientMethodsServices<Services, Callbacks> | APIQueryClientHooksServices<Services, Callbacks> | APIBasicQueryClientMethodsServices<Services, Callbacks> | APIBasicClientMethodsServices<Services, Callbacks> {
    if (callbacksOrOptions) {
        if ("requestFn" in callbacksOrOptions)
            return qraftReactAPIClient(services, callbacks, callbacksOrOptions);
        if ("queryClient" in callbacksOrOptions)
            return qraftReactAPIClient(services, callbacks, callbacksOrOptions);
    }
    return qraftReactAPIClient(services, callbacksOrOptions ?? callbacks, APIClientContext);
}
type DefaultCallbacks = typeof defaultCallbacks;
type AllCallbacks = typeof allCallbacks;
