/**
 * This file was auto-generated by @openapi-qraft/cli.
 * Do not make direct changes to the file.
 */

import type { APIBasicClientServices, APIBasicQueryClientServices, APIDefaultQueryClientServices, APIContextQueryClientServices, CreateAPIBasicClientOptions, CreateAPIBasicQueryClientOptions, CreateAPIClientOptions, CreateAPIQueryClientOptions } from "@openapi-qraft/react";
import { APIClientContext } from "./APIClientContext";
import * as allCallbacks from "@openapi-qraft/react/callbacks/index";
import { qraftAPIClient, qraftReactAPIClient } from "@openapi-qraft/react";
import { services } from "./services/index";
export function createAPIClient(options: CreateAPIQueryClientOptions): APIDefaultQueryClientServices<Services>;
export function createAPIClient(options: CreateAPIBasicQueryClientOptions): APIBasicQueryClientServices<Services, AllCallbacks>;
export function createAPIClient(options: CreateAPIBasicClientOptions): APIBasicClientServices<Services, AllCallbacks>;
export function createAPIClient(): APIContextQueryClientServices<Services, AllCallbacks>;
export function createAPIClient(options?: CreateAPIClientOptions): APIDefaultQueryClientServices<Services> | APIContextQueryClientServices<Services, AllCallbacks> | APIBasicQueryClientServices<Services, AllCallbacks> | APIBasicClientServices<Services, AllCallbacks> {
    if (options) {
        if ("requestFn" in options)
            return qraftAPIClient(services, allCallbacks, options);
        if ("queryClient" in options)
            return qraftAPIClient(services, allCallbacks, options);
    }
    return qraftReactAPIClient(services, allCallbacks, APIClientContext);
}
type AllCallbacks = typeof allCallbacks;
type Services = typeof services;
