/**
 * This file was auto-generated by @openapi-qraft/cli.
 * Do not make direct changes to the file.
 */

import type { APIBasicClientServices, APIBasicQueryClientServices, APIDefaultQueryClientServices, APIContextQueryClientServices, APIQueryClientServices, CreateAPIBasicClientOptions, CreateAPIBasicQueryClientOptions, CreateAPIClientOptions, CreateAPIQueryClientOptions, UnionServiceOperationsDeclaration } from "@openapi-qraft/react";
import { APIClientContext } from "./APIClientContext";
import type * as allCallbacks from "@openapi-qraft/react/callbacks/index";
import { qraftAPIClient } from "@openapi-qraft/react";
const defaultCallbacks = {} as const;
export function createAPIClient<Services extends UnionServiceOperationsDeclaration<Services>>(services: Services, options: CreateAPIQueryClientOptions, callbacks: AllCallbacks): APIDefaultQueryClientServices<Services>;
export function createAPIClient<Services extends UnionServiceOperationsDeclaration<Services>, Callbacks extends Partial<AllCallbacks> = DefaultCallbacks>(services: Services, options: CreateAPIQueryClientOptions, callbacks: Callbacks): APIQueryClientServices<Services, Callbacks>;
export function createAPIClient<Services extends UnionServiceOperationsDeclaration<Services>, Callbacks extends Partial<AllCallbacks> = DefaultCallbacks>(services: Services, options: CreateAPIBasicQueryClientOptions, callbacks: Callbacks): APIBasicQueryClientServices<Services, Callbacks>;
export function createAPIClient<Services extends UnionServiceOperationsDeclaration<Services>, Callbacks extends Partial<AllCallbacks> = DefaultCallbacks>(services: Services, options: CreateAPIBasicClientOptions, callbacks: Callbacks): APIBasicClientServices<Services, Callbacks>;
export function createAPIClient<Services extends UnionServiceOperationsDeclaration<Services>, Callbacks extends Partial<AllCallbacks> = DefaultCallbacks>(services: Services, callbacks: Callbacks): APIContextQueryClientServices<Services, Callbacks>;
export function createAPIClient<Services extends UnionServiceOperationsDeclaration<Services>, Callbacks extends Partial<AllCallbacks> = DefaultCallbacks>(services: Services, callbacksOrOptions: CreateAPIClientOptions | Callbacks, callbacks: Callbacks = defaultCallbacks as Callbacks): APIDefaultQueryClientServices<Services> | APIQueryClientServices<Services, Callbacks> | APIContextQueryClientServices<Services, Callbacks> | APIBasicQueryClientServices<Services, Callbacks> | APIBasicClientServices<Services, Callbacks> {
    if (callbacksOrOptions) {
        if ("requestFn" in callbacksOrOptions)
            return qraftAPIClient(services, callbacks, callbacksOrOptions);
        if ("queryClient" in callbacksOrOptions)
            return qraftAPIClient(services, callbacks, callbacksOrOptions);
    }
    return qraftAPIClient(services, callbacksOrOptions ?? callbacks, APIClientContext);
}
type DefaultCallbacks = typeof defaultCallbacks;
type AllCallbacks = typeof allCallbacks;
