/**
 * This file was auto-generated by @openapi-qraft/cli.
 * Do not make direct changes to the file.
 */

import type { CreateAPIQueryClientOptions } from "@openapi-qraft/react";
import { createContext } from "react";
export const APIClientContext = createContext<CreateAPIQueryClientOptions | undefined>(undefined);
