/**
 * This file was auto-generated by @openapi-qraft/cli.
 * Do not make direct changes to the file.
 */

import type { APIBasicClientMethodsServices, APIBasicQueryClientMethodsServices, APIQueryClientHooksServices, APIQueryClientMethodsServices, CreateAPIBasicClientOptions, CreateAPIBasicQueryClientOptions, CreateAPIClientOptions, CreateAPIQueryClientOptions } from "@openapi-qraft/react";
import { APIClientContext } from "./APIClientContext";
import * as allCallbacks from "@openapi-qraft/react/callbacks/index";
import { qraftReactAPIClient } from "@openapi-qraft/react";
import { services } from "./services/index";
export function createAPIClient(options: CreateAPIQueryClientOptions): APIQueryClientMethodsServices<Services, AllCallbacks>;
export function createAPIClient(options: CreateAPIBasicQueryClientOptions): APIBasicQueryClientMethodsServices<Services, AllCallbacks>;
export function createAPIClient(options: CreateAPIBasicClientOptions): APIBasicClientMethodsServices<Services, AllCallbacks>;
export function createAPIClient(): APIQueryClientHooksServices<Services, AllCallbacks>;
export function createAPIClient(options?: CreateAPIClientOptions): APIQueryClientMethodsServices<Services, AllCallbacks> | APIQueryClientHooksServices<Services, AllCallbacks> | APIBasicQueryClientMethodsServices<Services, AllCallbacks> | APIBasicClientMethodsServices<Services, AllCallbacks> {
    if (options) {
        if ("requestFn" in options)
            return qraftReactAPIClient(services, allCallbacks, options);
        if ("queryClient" in options)
            return qraftReactAPIClient(services, allCallbacks, options);
    }
    return qraftReactAPIClient(services, allCallbacks, APIClientContext);
}
type AllCallbacks = typeof allCallbacks;
type Services = typeof services;
