import type { AsyncAPIDocumentInterface } from '@qraft/asyncapi-plugin';
import type ts from 'typescript';
import type { AsyncAPIContext, AsyncAPITSOptions } from './types.js';
import { performance } from 'node:perf_hooks';
import { debug } from 'openapi-typescript/dist/lib/utils.js';
import transformAsyncAPISchema from './transform/index.js';

export * from './types.js';
export { astToString } from 'openapi-typescript/dist/lib/ts.js';

export const COMMENT_HEADER = `/**
 * This file was auto-generated by openapi-typescript (asyncapi).
 * Do not make direct changes to the file.
 */

`;

export interface AsyncAPITSInput {
  document: AsyncAPIDocumentInterface;
  rawSchema: Record<string, unknown>;
}

function resolveRef<T>(
  schema: Record<string, unknown>,
  $ref: string
): T | undefined {
  if (!$ref || !$ref.startsWith('#/')) {
    return undefined;
  }

  const parts = $ref.slice(2).split('/');
  let current: unknown = schema;

  for (const part of parts) {
    if (current && typeof current === 'object' && part in current) {
      current = (current as Record<string, unknown>)[part];
    } else {
      return undefined;
    }
  }

  return current as T;
}

export default function asyncapiTS(
  input: AsyncAPITSInput,
  options: AsyncAPITSOptions = {}
): ts.Node[] {
  const { document, rawSchema } = input;

  const ctx: AsyncAPIContext = {
    alphabetize: options.alphabetize ?? false,
    additionalProperties: options.additionalProperties ?? false,
    defaultNonNullable: options.defaultNonNullable ?? true,
    emptyObjectsUnknown: options.emptyObjectsUnknown ?? false,
    enum: options.enum ?? false,
    enumValues: options.enumValues ?? false,
    dedupeEnums: options.dedupeEnums ?? false,
    excludeDeprecated: options.excludeDeprecated ?? false,
    exportType: options.exportType ?? false,
    immutable: options.immutable ?? false,
    propertiesRequiredByDefault: options.propertiesRequiredByDefault ?? false,
    silent: options.silent ?? false,
    transform:
      typeof options.transform === 'function' ? options.transform : undefined,
    postTransform:
      typeof options.postTransform === 'function'
        ? options.postTransform
        : undefined,
    injectFooter: [],
    document,
    rawSchema,
    resolve<T>($ref: string): T | undefined {
      return resolveRef<T>(rawSchema, $ref);
    },
  };

  const transformT = performance.now();
  const result = transformAsyncAPISchema(ctx);
  debug(
    'Completed AST transformation for AsyncAPI document',
    'asyncapi',
    performance.now() - transformT
  );

  return result;
}
