import ts from 'typescript';

type Options = {
  servicesDirName: string;
  explicitImportExtensions: boolean;
};

export const getClientFactory = (options: Options) => {
  return [
    ...getClientImportsFactory(options),
    ...getCreateClientFunctionFactory(),
  ];
};

const getClientImportsFactory = ({
  servicesDirName,
  explicitImportExtensions,
}: Options) => {
  const factory = ts.factory;

  return [
    factory.createImportDeclaration(
      undefined,
      factory.createImportClause(
        false,
        undefined,
        factory.createNamedImports([
          factory.createImportSpecifier(
            false,
            undefined,
            factory.createIdentifier('qraftAPIClient')
          ),
          ...[
            'APIBasicClientServices',
            'APIBasicQueryClientServices',
            'APIUtilityClientServices',
            'CreateAPIBasicQueryClientOptions',
            'CreateAPIBasicClientOptions',
            'CreateAPIClientOptions',
            'CreateAPIQueryClientOptions',
          ].map((name) =>
            factory.createImportSpecifier(
              true,
              undefined,
              factory.createIdentifier(name)
            )
          ),
        ])
      ),
      factory.createStringLiteral('@openapi-qraft/react'),
      undefined
    ),
    factory.createImportDeclaration(
      undefined,
      factory.createImportClause(
        false,
        undefined,
        factory.createNamespaceImport(factory.createIdentifier('callbacks'))
      ),
      factory.createStringLiteral('@openapi-qraft/react/callbacks/index'),
      undefined
    ),
    factory.createImportDeclaration(
      undefined,
      factory.createImportClause(
        false,
        undefined,
        factory.createNamedImports([
          factory.createImportSpecifier(
            false,
            undefined,
            factory.createIdentifier('services')
          ),
          factory.createImportSpecifier(
            true,
            undefined,
            factory.createIdentifier('Services')
          ),
        ])
      ),
      factory.createStringLiteral(
        `./${servicesDirName}/index${explicitImportExtensions ? '.js' : ''}`
      ),
      undefined
    ),
  ];
};

const getCreateClientFunctionFactory = () => {
  const factory = ts.factory;

  return [
    factory.createFunctionDeclaration(
      [factory.createToken(ts.SyntaxKind.ExportKeyword)],
      undefined,
      factory.createIdentifier('createAPIClient'),
      undefined,
      [
        factory.createParameterDeclaration(
          undefined,
          undefined,
          factory.createIdentifier('options'),
          undefined,
          factory.createTypeReferenceNode(
            factory.createIdentifier('CreateAPIQueryClientOptions'),
            undefined
          ),
          undefined
        ),
      ],
      factory.createTypeReferenceNode(
        factory.createIdentifier('Services'),
        undefined
      ),
      undefined
    ),
    factory.createFunctionDeclaration(
      [factory.createToken(ts.SyntaxKind.ExportKeyword)],
      undefined,
      factory.createIdentifier('createAPIClient'),
      undefined,
      [
        factory.createParameterDeclaration(
          undefined,
          undefined,
          factory.createIdentifier('options'),
          undefined,
          factory.createTypeReferenceNode(
            factory.createIdentifier('CreateAPIBasicQueryClientOptions'),
            undefined
          ),
          undefined
        ),
      ],
      factory.createTypeReferenceNode(
        factory.createIdentifier('APIBasicQueryClientServices'),
        [
          factory.createTypeReferenceNode(
            factory.createIdentifier('Services'),
            undefined
          ),
          factory.createTypeReferenceNode(
            factory.createIdentifier('ServiceMethods'),
            undefined
          ),
        ]
      ),
      undefined
    ),
    factory.createFunctionDeclaration(
      [factory.createToken(ts.SyntaxKind.ExportKeyword)],
      undefined,
      factory.createIdentifier('createAPIClient'),
      undefined,
      [
        factory.createParameterDeclaration(
          undefined,
          undefined,
          factory.createIdentifier('options'),
          undefined,
          factory.createTypeReferenceNode(
            factory.createIdentifier('CreateAPIBasicClientOptions'),
            undefined
          ),
          undefined
        ),
      ],
      factory.createTypeReferenceNode(
        factory.createIdentifier('APIBasicClientServices'),
        [
          factory.createTypeReferenceNode(
            factory.createIdentifier('Services'),
            undefined
          ),
          factory.createTypeReferenceNode(
            factory.createIdentifier('ServiceMethods'),
            undefined
          ),
        ]
      ),
      undefined
    ),
    factory.createFunctionDeclaration(
      [factory.createToken(ts.SyntaxKind.ExportKeyword)],
      undefined,
      factory.createIdentifier('createAPIClient'),
      undefined,
      [],
      factory.createTypeReferenceNode(
        factory.createIdentifier('APIUtilityClientServices'),
        [
          factory.createTypeReferenceNode(
            factory.createIdentifier('Services'),
            undefined
          ),
          factory.createTypeReferenceNode(
            factory.createIdentifier('ServiceMethods'),
            undefined
          ),
        ]
      ),
      undefined
    ),
    factory.createFunctionDeclaration(
      [factory.createToken(ts.SyntaxKind.ExportKeyword)],
      undefined,
      factory.createIdentifier('createAPIClient'),
      undefined,
      [
        factory.createParameterDeclaration(
          undefined,
          undefined,
          factory.createIdentifier('options'),
          factory.createToken(ts.SyntaxKind.QuestionToken),
          factory.createTypeReferenceNode(
            factory.createIdentifier('CreateAPIClientOptions'),
            undefined
          ),
          undefined
        ),
      ],
      factory.createUnionTypeNode([
        factory.createTypeReferenceNode(
          factory.createIdentifier('Services'),
          undefined
        ),
        factory.createTypeReferenceNode(
          factory.createIdentifier('APIBasicClientServices'),
          [
            factory.createTypeReferenceNode(
              factory.createIdentifier('Services'),
              undefined
            ),
            factory.createTypeReferenceNode(
              factory.createIdentifier('ServiceMethods'),
              undefined
            ),
          ]
        ),
        factory.createTypeReferenceNode(
          factory.createIdentifier('APIUtilityClientServices'),
          [
            factory.createTypeReferenceNode(
              factory.createIdentifier('Services'),
              undefined
            ),
            factory.createTypeReferenceNode(
              factory.createIdentifier('ServiceMethods'),
              undefined
            ),
          ]
        ),
      ]),
      factory.createBlock(
        [
          factory.createIfStatement(
            factory.createPrefixUnaryExpression(
              ts.SyntaxKind.ExclamationToken,
              factory.createIdentifier('options')
            ),
            factory.createReturnStatement(
              factory.createCallExpression(
                factory.createIdentifier('qraftAPIClient'),
                [
                  factory.createTypeReferenceNode(
                    factory.createIdentifier('Services'),
                    undefined
                  ),
                  factory.createTypeReferenceNode(
                    factory.createIdentifier('ServiceMethods'),
                    undefined
                  ),
                ],
                [
                  factory.createIdentifier('services'),
                  factory.createIdentifier('callbacks'),
                ]
              )
            ),
            undefined
          ),
          factory.createIfStatement(
            factory.createBinaryExpression(
              factory.createStringLiteral('requestFn'),
              factory.createToken(ts.SyntaxKind.InKeyword),
              factory.createIdentifier('options')
            ),
            factory.createReturnStatement(
              factory.createCallExpression(
                factory.createIdentifier('qraftAPIClient'),
                [
                  factory.createTypeReferenceNode(
                    factory.createIdentifier('Services'),
                    undefined
                  ),
                  factory.createTypeReferenceNode(
                    factory.createIdentifier('ServiceMethods'),
                    undefined
                  ),
                ],
                [
                  factory.createIdentifier('services'),
                  factory.createIdentifier('callbacks'),
                  factory.createIdentifier('options'),
                ]
              )
            ),
            undefined
          ),
          factory.createReturnStatement(
            factory.createCallExpression(
              factory.createIdentifier('qraftAPIClient'),
              [
                factory.createTypeReferenceNode(
                  factory.createIdentifier('Services'),
                  undefined
                ),
                factory.createTypeReferenceNode(
                  factory.createIdentifier('ServiceMethods'),
                  undefined
                ),
              ],
              [
                factory.createIdentifier('services'),
                factory.createIdentifier('callbacks'),
                factory.createIdentifier('options'),
              ]
            )
          ),
        ],
        true
      )
    ),
    factory.createTypeAliasDeclaration(
      undefined,
      factory.createIdentifier('ServiceMethods'),
      undefined,
      factory.createTypeQueryNode(
        factory.createIdentifier('callbacks'),
        undefined
      )
    ),
  ];
};
