/**
 * This file was auto-generated by @openapi-qraft/cli.
 * Do not make direct changes to the file.
 */

import type { RequestFn } from "../type-overrides/qraft-predefined-parameters.js";
import type { QraftPredefinedParameterValue } from "../type-overrides/qraft-predefined-parameters.js";
import { qraftPredefinedParametersRequestFn } from "@openapi-qraft/react/qraftPredefinedParametersRequestFn";
import type { paths } from "./../openapi.d.ts";
export type ServiceOperationsPredefinedParameters = [
    {
        requestPattern: "post /entities/{entity_id}/documents";
        parameters: [
            {
                in: "header";
                name: "x-monite-version";
                value: QraftPredefinedParameterValue<NonNullable<paths["/entities/{entity_id}/documents"]["post"]["parameters"]["header"]>["x-monite-version"]>;
            }
        ];
    },
    {
        requestPattern: "get,delete,patch /approval_policies/{approval_policy_id}/**";
        parameters: [
            {
                in: "header";
                name: "x-monite-entity-id";
                value: QraftPredefinedParameterValue<NonNullable<paths["/approval_policies/{approval_policy_id}"]["get"]["parameters"]["header"]>["x-monite-entity-id"]>;
            }
        ];
    }
];
export const serviceOperationsPredefinedParameters = [
    {
        requestPattern: "post /entities/{entity_id}/documents",
        methods: ["post"],
        paths: [
            "/entities/{entity_id}/documents"
        ]
    },
    {
        requestPattern: "get,delete,patch /approval_policies/{approval_policy_id}/**",
        methods: ["get", "delete", "patch"],
        paths: [
            "/approval_policies/{approval_policy_id}"
        ]
    }
] as const;
export function createPredefinedParametersRequestFn<TRequestFn extends RequestFn<any, any>>(predefinedParameters: ServiceOperationsPredefinedParameters, requestFn: TRequestFn): TRequestFn {
    return qraftPredefinedParametersRequestFn(predefinedParameters, serviceOperationsPredefinedParameters, requestFn) as TRequestFn;
}
