/**
 * This file was auto-generated by @openapi-qraft/cli.
 * Do not make direct changes to the file.
 */

import type { APIBasicClientServices, APIBasicQueryClientServices, APIDefaultQueryClientServices, APIQueryClientServices, APIUtilityClientServices, CreateAPIBasicClientOptions, CreateAPIBasicQueryClientOptions, CreateAPIClientOptions, CreateAPIQueryClientOptions, UnionServiceOperationsDeclaration } from "@openapi-qraft/react";
import * as allCallbacks from "@openapi-qraft/react/callbacks/index";
import { qraftAPIClient } from "@openapi-qraft/react";
export function createAPIOperationClient<Services extends UnionServiceOperationsDeclaration<Services>, Callbacks extends AllCallbacks>(services: Services, options: CreateAPIQueryClientOptions, callbacks?: Callbacks): APIDefaultQueryClientServices<Services>;
export function createAPIOperationClient<Services extends UnionServiceOperationsDeclaration<Services>, Callbacks extends Partial<AllCallbacks> = AllCallbacks>(services: Services, options: CreateAPIQueryClientOptions, callbacks?: Callbacks): APIQueryClientServices<Services, Callbacks>;
export function createAPIOperationClient<Services extends UnionServiceOperationsDeclaration<Services>, Callbacks extends Partial<AllCallbacks> = AllCallbacks>(services: Services, options: CreateAPIBasicQueryClientOptions, callbacks?: Callbacks): APIBasicQueryClientServices<Services, AllCallbacks>;
export function createAPIOperationClient<Services extends UnionServiceOperationsDeclaration<Services>, Callbacks extends Partial<AllCallbacks> = AllCallbacks>(services: Services, options: CreateAPIBasicClientOptions, callbacks?: Callbacks): APIBasicClientServices<Services, AllCallbacks>;
export function createAPIOperationClient<Services extends UnionServiceOperationsDeclaration<Services>, Callbacks extends Partial<AllCallbacks> = AllCallbacks>(services: Services, callbacks?: Callbacks): APIUtilityClientServices<Services, Callbacks>;
export function createAPIOperationClient<Services extends UnionServiceOperationsDeclaration<Services>, Callbacks extends Partial<AllCallbacks> = AllCallbacks>(services: Services, callbacksOrOptions?: CreateAPIClientOptions | Callbacks, callbacks: Callbacks = allCallbacks as Callbacks): APIDefaultQueryClientServices<Services> | APIQueryClientServices<Services, Callbacks> | APIBasicQueryClientServices<Services, Callbacks> | APIBasicClientServices<Services, Callbacks> | APIUtilityClientServices<Services, Callbacks> {
    if (!callbacksOrOptions)
        return qraftAPIClient(services, callbacks);
    if ("requestFn" in callbacksOrOptions)
        return qraftAPIClient(services, callbacks, callbacksOrOptions);
    if ("queryClient" in callbacksOrOptions)
        return qraftAPIClient(services, callbacks, callbacksOrOptions);
    return qraftAPIClient(services, callbacksOrOptions);
}
type AllCallbacks = typeof allCallbacks;
