import type { Readable } from 'node:stream';
import type ts from 'typescript';
import type { OpenAPI3, OpenAPITSOptions } from './types.js';

export * from './lib/ts.js';
export * from './lib/utils.js';
export { default as transformSchema } from './transform/index.js';
export { default as transformComponentsObject } from './transform/components-object.js';
export { default as transformHeaderObject } from './transform/header-object.js';
export { default as transformMediaTypeObject } from './transform/media-type-object.js';
export * from './transform/operation-object.js';
export { default as transformOperationObject } from './transform/operation-object.js';
export { default as transformParameterObject } from './transform/parameter-object.js';
export * from './transform/path-item-object.js';
export { default as transformPathItemObject } from './transform/path-item-object.js';
export { default as transformPathsObject } from './transform/paths-object.js';
export { default as transformRequestBodyObject } from './transform/request-body-object.js';
export { default as transformResponseObject } from './transform/response-object.js';
export { default as transformResponsesObject } from './transform/responses-object.js';
export * from './transform/schema-object.js';
export { default as transformSchemaObject } from './transform/schema-object.js';
export * from './types.js';
export declare const COMMENT_HEADER =
  '/**\n * This file was auto-generated by openapi-typescript.\n * Do not make direct changes to the file.\n */\n\n';
export default function openapiTS(
  source: string | URL | OpenAPI3 | Buffer | Readable,
  options?: OpenAPITSOptions
): Promise<ts.Node[]>;
