export function createFileHeader(cliName: string): string {
  return `/**
 * This file was auto-generated by ${cliName}.
 * Do not make direct changes to the file.
 */

`;
}

// @deprecated Use createFileHeader instead.
export const fileHeader = createFileHeader('@openapi-qraft/cli');
