/**
 * This file was auto-generated by @openapi-qraft/cli.
 * Do not make direct changes to the file.
 */

export interface servers {
    readonly "events-test": {
        readonly host: "test-events.example.com";
        readonly protocol: "ws";
        readonly description: "Test WebSocket server for events (lighting measurements)";
    };
    readonly "events-prod": {
        readonly host: "prod-events.example.com";
        readonly protocol: "wss";
        readonly description: "Production WebSocket server for events (lighting measurements) secured with TLS";
    };
    readonly "commands-test": {
        readonly host: "test-commands.example.com";
        readonly protocol: "ws";
        readonly description: "Test WebSocket server for commands (turn on/off, dim)";
    };
    readonly "commands-prod": {
        readonly host: "prod-commands.example.com";
        readonly protocol: "wss";
        readonly description: "Production WebSocket server for commands (turn on/off, dim) secured with TLS";
    };
}
export interface channels {
    readonly lightingMeasured: {
        readonly address: "/events/streetlights/{streetlightId}/lighting/measured";
        readonly messages: {
            readonly lightMeasured: unknown;
            readonly lightMeasuredResponse: unknown;
        };
        readonly parameters: {
            readonly streetlightId: unknown;
        };
    };
    readonly lightTurnOn: {
        readonly address: "/commands/streetlights/{streetlightId}/turn/on";
        readonly messages: {
            readonly turnOn: unknown;
            readonly turnOnResponse: unknown;
        };
        readonly parameters: {
            readonly streetlightId: unknown;
        };
    };
    readonly lightTurnOff: {
        readonly address: "/commands/streetlights/{streetlightId}/turn/off";
        readonly messages: {
            readonly turnOff: unknown;
            readonly turnOffResponse: unknown;
        };
        readonly parameters: {
            readonly streetlightId: unknown;
        };
    };
    readonly lightsDim: {
        readonly address: "/commands/streetlights/{streetlightId}/dim";
        readonly messages: {
            readonly dimLight: unknown;
            readonly dimLightResponse: unknown;
        };
        readonly parameters: {
            readonly streetlightId: unknown;
        };
    };
    readonly lightTurnOnDynamicReply: {
        readonly address: null;
        readonly messages: {
            readonly turnOnDynamicResponse: unknown;
        };
    };
    readonly lightTurnOffDynamicReply: {
        readonly address: null;
        readonly messages: {
            readonly turnOffDynamicResponse: unknown;
        };
    };
    readonly lightsDimDynamicReply: {
        readonly address: null;
        readonly messages: {
            readonly dimDynamicResponse: unknown;
        };
    };
    readonly heartbeat: {
        readonly address: "/system/heartbeat";
        readonly messages: {
            readonly heartbeat: unknown;
        };
    };
}
export interface operations {
    readonly sendLightMeasurement: {
        readonly action: "send";
        readonly summary: "Server sends environmental lighting conditions of a particular streetlight to subscribers.";
    };
    readonly receiveLightMeasurement: {
        readonly action: "receive";
        readonly summary: "Server receives light measurement data from a sensor and responds with acknowledgment.";
    };
    readonly sendLightMeasurementForAnalytics: {
        readonly action: "send";
        readonly summary: "Server sends light measurement data for analytics processing.";
    };
    readonly sendLightMeasurementWithAck: {
        readonly action: "send";
        readonly summary: "Server sends light measurement data and expects acknowledgment from the client.";
    };
    readonly sendTurnOnWithDynamicReply: {
        readonly action: "send";
        readonly reply: {
            readonly address: {
                readonly location: "$message.header#/replyTo";
                readonly description: "Reply address extracted from message header replyTo field";
            };
        };
        readonly summary: "Server sends turn on command and expects response on a dynamic address from message header.";
    };
    readonly receiveTurnOn: {
        readonly action: "receive";
        readonly reply: {
            readonly address: {
                readonly location: "$message.header#/replyTo";
                readonly description: "Reply address extracted from message header replyTo field";
            };
        };
        readonly summary: "Server receives command to turn on a streetlight and responds with execution result.";
    };
    readonly receiveTurnOff: {
        readonly action: "receive";
        readonly reply: {
            readonly address: {
                readonly location: "$message.header#/replyTo";
                readonly description: "Inline reply address extracted from message header";
            };
        };
        readonly summary: "Server receives command to turn off a streetlight and responds with execution result.";
    };
    readonly receiveDimLight: {
        readonly action: "receive";
        readonly reply: {
            readonly address: {
                readonly location: "$message.payload#/responseAddress";
                readonly description: "Reply address extracted from message payload responseAddress field";
            };
        };
        readonly summary: "Server receives command to dim a streetlight and responds with execution result.";
    };
    readonly sendHeartbeat: {
        readonly action: "send";
        readonly summary: "Server periodically sends heartbeat messages to all connected clients to verify connection health.";
    };
    readonly receiveHeartbeat: {
        readonly action: "receive";
        readonly summary: "Server receives heartbeat messages from clients to confirm they are still connected.";
    };
}
export interface components {
    schemas: {
        readonly lightMeasuredPayload: {
            /** @description Light intensity measured in lumens. */
            readonly lumens?: number;
            /**
             * Format: date-time
             * @description Date and time when the message was sent.
             */
            readonly sentAt?: string;
        };
        readonly measurementResponsePayload: {
            /** @description Indicates whether the measurement was successfully received. */
            readonly received?: boolean;
            /**
             * Format: date-time
             * @description Date and time when the message was sent.
             */
            readonly processedAt?: string;
        };
        readonly turnOnOffPayload: {
            /**
             * @description Whether to turn on or off the light.
             * @enum {string}
             */
            readonly command?: "on" | "off";
            /**
             * Format: date-time
             * @description Date and time when the message was sent.
             */
            readonly sentAt?: string;
        };
        readonly dimLightPayload: {
            /** @description Percentage to which the light should be dimmed to. */
            readonly percentage?: number;
            /**
             * Format: date-time
             * @description Date and time when the message was sent.
             */
            readonly sentAt?: string;
        };
        readonly commandResponsePayload: {
            /** @description Indicates whether the command was executed successfully. */
            readonly success?: boolean;
            /** @description Human-readable message about the command execution result. */
            readonly message?: string;
            /**
             * Format: date-time
             * @description Date and time when the message was sent.
             */
            readonly executedAt?: string;
        };
        /**
         * Format: date-time
         * @description Date and time when the message was sent.
         */
        readonly sentAt: string;
        readonly dynamicCommandResponsePayload: {
            /** @description Indicates whether the command was executed successfully. */
            readonly success: boolean;
            /** @description Human-readable message about the command execution result. */
            readonly message?: string;
            /**
             * Format: date-time
             * @description Date and time when the message was sent.
             */
            readonly executedAt?: string;
            /** @description The dynamic address where this response was sent. */
            readonly dynamicAddress?: string;
        };
        readonly heartbeatPayload: {
            /**
             * Format: date-time
             * @description Date and time when the message was sent.
             */
            readonly timestamp: string;
            /** @description Server timestamp in milliseconds since Unix epoch. */
            readonly serverTime?: number;
            /** @description Monotonically increasing sequence number for heartbeat messages. */
            readonly sequenceNumber: number;
        };
    };
    messages: {
        /**
         * Light measured
         * Inform about environmental lighting conditions of a particular streetlight.
         */
        readonly lightMeasured: {
            readonly name: "lightMeasured";
            readonly payload?: {
                /** @description Light intensity measured in lumens. */
                readonly lumens?: number;
                /**
                 * Format: date-time
                 * @description Date and time when the message was sent.
                 */
                readonly sentAt?: string;
            };
            readonly headers: {
                readonly "my-app-header"?: number;
                /** @description Address to reply to */
                readonly replyTo?: string;
                /** @description Correlation identifier for request/reply matching. */
                readonly reqid: string;
            };
            readonly contentType: "application/json";
            readonly correlationId: {
                readonly location: "$message.header#/reqid";
                readonly description: "Correlation ID.";
            };
        };
        /**
         * Light measurement acknowledgment
         * Acknowledgment response for received light measurement data.
         */
        readonly lightMeasuredResponse: {
            readonly name: "lightMeasuredResponse";
            readonly payload?: {
                /** @description Indicates whether the measurement was successfully received. */
                readonly received?: boolean;
                /**
                 * Format: date-time
                 * @description Date and time when the message was sent.
                 */
                readonly processedAt?: string;
            };
            readonly headers?: {
                readonly "my-app-header"?: number;
                /** @description Address to reply to */
                readonly replyTo?: string;
                /** @description Correlation identifier for request/reply matching. */
                readonly reqid?: string;
            };
            readonly contentType: "application/json";
            readonly correlationId: {
                readonly location: "$message.header#/reqid";
                readonly description: "Correlation ID.";
            };
        };
        /**
         * Turn on/off
         * Command a particular streetlight to turn the lights on or off.
         */
        readonly turnOnOff: {
            readonly name: "turnOnOff";
            readonly payload?: {
                /**
                 * @description Whether to turn on or off the light.
                 * @enum {string}
                 */
                readonly command?: "on" | "off";
                /**
                 * Format: date-time
                 * @description Date and time when the message was sent.
                 */
                readonly sentAt?: string;
            };
            readonly headers: {
                readonly "my-app-header"?: number;
                /** @description Address to reply to */
                readonly replyTo?: string;
                /** @description Correlation identifier for request/reply matching. */
                readonly reqid: string;
            };
            readonly correlationId: {
                readonly location: "$message.header#/reqid";
                readonly description: "Correlation ID.";
            };
        };
        /**
         * Dim light
         * Command a particular streetlight to dim the lights.
         */
        readonly dimLight: {
            readonly name: "dimLight";
            readonly payload?: {
                /** @description Percentage to which the light should be dimmed to. */
                readonly percentage?: number;
                /**
                 * Format: date-time
                 * @description Date and time when the message was sent.
                 */
                readonly sentAt?: string;
            };
            readonly headers: {
                readonly "my-app-header"?: number;
                /** @description Address to reply to */
                readonly replyTo?: string;
                /** @description Correlation identifier for request/reply matching. */
                readonly reqid: string;
            };
            readonly correlationId: {
                readonly location: "$message.header#/reqid";
                readonly description: "Correlation ID.";
            };
        };
        /**
         * Command response
         * Response to a command execution with status and details.
         */
        readonly commandResponse: {
            readonly name: "commandResponse";
            readonly payload?: {
                /** @description Indicates whether the command was executed successfully. */
                readonly success?: boolean;
                /** @description Human-readable message about the command execution result. */
                readonly message?: string;
                /**
                 * Format: date-time
                 * @description Date and time when the message was sent.
                 */
                readonly executedAt?: string;
            };
            readonly headers?: {
                readonly "my-app-header"?: number;
                /** @description Address to reply to */
                readonly replyTo?: string;
            };
            readonly contentType: "application/json";
        };
        /**
         * Dynamic command response
         * Response sent to a dynamically determined address.
         */
        readonly dynamicCommandResponse: {
            readonly name: "dynamicCommandResponse";
            readonly payload: {
                /** @description Indicates whether the command was executed successfully. */
                readonly success: boolean;
                /** @description Human-readable message about the command execution result. */
                readonly message?: string;
                /**
                 * Format: date-time
                 * @description Date and time when the message was sent.
                 */
                readonly executedAt?: string;
                /** @description The dynamic address where this response was sent. */
                readonly dynamicAddress?: string;
            };
            readonly headers?: {
                /** @description Address to reply to */
                readonly replyTo?: string;
                /** @description Correlation identifier for request/reply matching. */
                readonly reqid?: string;
            };
            readonly contentType: "application/json";
            readonly correlationId: {
                readonly location: "$message.header#/reqid";
                readonly description: "Request ID.";
            };
        };
        /**
         * Server heartbeat
         * Periodic heartbeat message sent by the server to verify connection health.
         */
        readonly heartbeat: {
            readonly name: "heartbeat";
            readonly payload: {
                /**
                 * Format: date-time
                 * @description Date and time when the message was sent.
                 */
                readonly timestamp: string;
                /** @description Server timestamp in milliseconds since Unix epoch. */
                readonly serverTime?: number;
                /** @description Monotonically increasing sequence number for heartbeat messages. */
                readonly sequenceNumber: number;
            };
            readonly headers?: {
                readonly "my-app-header"?: number;
                /** @description Address to reply to */
                readonly replyTo?: string;
            };
            readonly contentType: "application/json";
        };
    };
    parameters: {
        /** @description The ID of the streetlight. */
        readonly streetlightId: {
            readonly description: "The ID of the streetlight.";
            readonly location: "$message.payload#/item/id";
        };
    };
    securitySchemes: {
        readonly bearerAuth: {
            readonly type: "http";
            readonly description: "Bearer token authentication";
        };
    };
    servers: {
        readonly "events-test": {
            readonly host: "test-events.example.com";
            readonly protocol: "ws";
            readonly description: "Test WebSocket server for events (lighting measurements)";
        };
        readonly "commands-prod": {
            readonly host: "prod-commands.example.com";
            readonly protocol: "wss";
            readonly description: "Production WebSocket server for commands (turn on/off, dim) secured with TLS";
        };
    };
    messageTraits: {
        readonly correlationId: {
            readonly correlationId: {
                readonly location: "$message.header#/reqid";
                readonly description: "Correlation ID for request-reply matching, extracted from message header.";
            };
        };
        readonly commonHeaders: {
            readonly headers?: {
                readonly "my-app-header"?: number;
                /** @description Address to reply to */
                readonly replyTo?: string;
            };
        };
        readonly optionalReplyHeaders: {
            readonly headers?: {
                /** @description Address to reply to */
                readonly replyTo?: string;
                /** @description Correlation identifier for request/reply matching. */
                readonly reqid?: string;
            };
        };
    };
    operationTraits: {
        readonly websocket: {
            readonly bindings: unknown;
        };
    };
    replyAddresses: {
        /** @description Reply address extracted from message header replyTo field */
        readonly turnOnReplyAddress: {
            readonly location: "$message.header#/replyTo";
            readonly description: "Reply address extracted from message header replyTo field";
        };
        /** @description Reply address extracted from message payload responseAddress field */
        readonly dimLightReplyAddress: {
            readonly location: "$message.payload#/responseAddress";
            readonly description: "Reply address extracted from message payload responseAddress field";
        };
    };
    correlationIds: {
        /** @description Request ID. */
        readonly reqid: {
            readonly location: "$message.header#/reqid";
            readonly description: "Request ID.";
        };
    };
}
