/**
 * This file was auto-generated by @qraft/cli.
 * Do not make direct changes to the file.
 */

export interface servers {
    "events-test": components["servers"]["events-test"];
    "events-prod": {
        host: "prod-events.example.com";
        protocol: "wss";
        description: "Production WebSocket server for events (lighting measurements) secured with TLS";
    };
    "commands-test": {
        host: "test-commands.example.com";
        protocol: "ws";
        description: "Test WebSocket server for commands (turn on/off, dim)";
    };
    "commands-prod": components["servers"]["commands-prod"];
}
export interface channels {
    lightingMeasured: {
        address: "/events/streetlights/{streetlightId}/lighting/measured";
        messages: {
            lightMeasured: components["messages"]["lightMeasured"];
            lightMeasuredResponse: components["messages"]["lightMeasuredResponse"];
        };
        parameters: {
            streetlightId: "streetlight-1" | "streetlight-2";
        };
        servers: [
            servers["events-test"],
            servers["events-prod"]
        ];
    };
    lightTurnOn: {
        address: "/commands/streetlights/{streetlightId}/turn/on";
        messages: {
            turnOn: components["messages"]["turnOnOff"];
            turnOnResponse: components["messages"]["commandResponse"];
        };
        parameters: {
            streetlightId: "streetlight-1" | "streetlight-2";
        };
        servers: [
            servers["commands-test"],
            servers["commands-prod"]
        ];
    };
    lightTurnOff: {
        address: "/commands/streetlights/{streetlightId}/turn/off";
        messages: {
            turnOff: components["messages"]["turnOnOff"];
            turnOffResponse: components["messages"]["commandResponse"];
        };
        parameters: {
            streetlightId: "streetlight-1" | "streetlight-2";
        };
        servers: [
            servers["commands-test"],
            servers["commands-prod"]
        ];
    };
    lightsDim: {
        address: "/commands/streetlights/{streetlightId}/dim";
        messages: {
            dimLight: components["messages"]["dimLight"];
            dimLightResponse: components["messages"]["commandResponse"];
        };
        parameters: {
            streetlightId: "streetlight-1" | "streetlight-2";
        };
        servers: [
            servers["commands-test"],
            servers["commands-prod"]
        ];
    };
    lightTurnOnDynamicReply: {
        address: null;
        messages: {
            turnOnDynamicResponse: components["messages"]["dynamicCommandResponse"];
        };
        servers: [
            servers["commands-test"],
            servers["commands-prod"]
        ];
    };
    lightTurnOffDynamicReply: {
        address: null;
        messages: {
            turnOffDynamicResponse: components["messages"]["dynamicCommandResponse"];
        };
        servers: [
            servers["commands-test"],
            servers["commands-prod"]
        ];
    };
    lightsDimDynamicReply: {
        address: null;
        messages: {
            dimDynamicResponse: components["messages"]["dynamicCommandResponse"];
        };
        servers: [
            servers["commands-test"],
            servers["commands-prod"]
        ];
    };
    heartbeat: {
        address: "/system/heartbeat";
        messages: {
            heartbeat: components["messages"]["heartbeat"];
        };
        servers: [
            servers["events-test"],
            servers["events-prod"],
            servers["commands-test"],
            servers["commands-prod"]
        ];
    };
}
export interface operations {
    sendLightMeasurement: {
        action: "send";
        channel: channels["lightingMeasured"];
        messages: [
            channels["lightingMeasured"]["messages"]["lightMeasured"]
        ];
        summary: "Server sends environmental lighting conditions of a particular streetlight to subscribers.";
    };
    receiveLightMeasurement: {
        action: "receive";
        channel: channels["lightingMeasured"];
        messages: [
            channels["lightingMeasured"]["messages"]["lightMeasured"]
        ];
        reply: {
            channel: channels["lightingMeasured"];
            messages: [
                channels["lightingMeasured"]["messages"]["lightMeasuredResponse"]
            ];
        };
        summary: "Server receives light measurement data from a sensor and responds with acknowledgment.";
    };
    sendLightMeasurementForAnalytics: {
        action: "send";
        channel: channels["lightingMeasured"];
        messages: [
            channels["lightingMeasured"]["messages"]["lightMeasured"]
        ];
        summary: "Server sends light measurement data for analytics processing.";
    };
    sendLightMeasurementWithAck: {
        action: "send";
        channel: channels["lightingMeasured"];
        messages: [
            channels["lightingMeasured"]["messages"]["lightMeasured"]
        ];
        reply: {
            messages: [
                channels["lightingMeasured"]["messages"]["lightMeasuredResponse"]
            ];
        };
        summary: "Server sends light measurement data and expects acknowledgment from the client.";
    };
    sendTurnOnWithDynamicReply: {
        action: "send";
        channel: channels["lightTurnOn"];
        messages: [
            channels["lightTurnOn"]["messages"]["turnOn"]
        ];
        reply: {
            address: components["replyAddresses"]["turnOnReplyAddress"];
            channel: channels["lightTurnOnDynamicReply"];
            messages: [
                channels["lightTurnOnDynamicReply"]["messages"]["turnOnDynamicResponse"]
            ];
        };
        summary: "Server sends turn on command and expects response on a dynamic address from message header.";
    };
    receiveTurnOn: {
        action: "receive";
        channel: channels["lightTurnOn"];
        messages: [
            channels["lightTurnOn"]["messages"]["turnOn"]
        ];
        reply: {
            address: components["replyAddresses"]["turnOnReplyAddress"];
            channel: channels["lightTurnOnDynamicReply"];
            messages: [
                channels["lightTurnOnDynamicReply"]["messages"]["turnOnDynamicResponse"]
            ];
        };
        summary: "Server receives command to turn on a streetlight and responds with execution result.";
    };
    receiveTurnOff: {
        action: "receive";
        channel: channels["lightTurnOff"];
        messages: [
            channels["lightTurnOff"]["messages"]["turnOff"]
        ];
        reply: {
            address: {
                location: "$message.header#/replyTo";
                description: "Inline reply address extracted from message header";
            };
            channel: channels["lightTurnOffDynamicReply"];
            messages: [
                channels["lightTurnOffDynamicReply"]["messages"]["turnOffDynamicResponse"]
            ];
        };
        summary: "Server receives command to turn off a streetlight and responds with execution result.";
    };
    receiveDimLight: {
        action: "receive";
        channel: channels["lightsDim"];
        messages: [
            channels["lightsDim"]["messages"]["dimLight"]
        ];
        reply: {
            address: components["replyAddresses"]["dimLightReplyAddress"];
            channel: channels["lightsDimDynamicReply"];
            messages: [
                channels["lightsDimDynamicReply"]["messages"]["dimDynamicResponse"]
            ];
        };
        summary: "Server receives command to dim a streetlight and responds with execution result.";
    };
    sendHeartbeat: {
        action: "send";
        channel: channels["heartbeat"];
        messages: [
            channels["heartbeat"]["messages"]["heartbeat"]
        ];
        summary: "Server periodically sends heartbeat messages to all connected clients to verify connection health.";
    };
    receiveHeartbeat: {
        action: "receive";
        channel: channels["heartbeat"];
        messages: [
            channels["heartbeat"]["messages"]["heartbeat"]
        ];
        summary: "Server receives heartbeat messages from clients to confirm they are still connected.";
    };
}
export interface components {
    schemas: {
        lightMeasuredPayload: {
            /** @description Light intensity measured in lumens. */
            lumens?: number;
            sentAt?: components["schemas"]["sentAt"];
        };
        measurementResponsePayload: {
            /** @description Indicates whether the measurement was successfully received. */
            received?: boolean;
            processedAt?: components["schemas"]["sentAt"];
        };
        turnOnOffPayload: {
            /**
             * @description Whether to turn on or off the light.
             * @enum {string}
             */
            command?: "on" | "off";
            sentAt?: components["schemas"]["sentAt"];
        };
        dimLightPayload: {
            /** @description Percentage to which the light should be dimmed to. */
            percentage?: number;
            sentAt?: components["schemas"]["sentAt"];
        };
        commandResponsePayload: {
            /** @description Indicates whether the command was executed successfully. */
            success?: boolean;
            /** @description Human-readable message about the command execution result. */
            message?: string;
            executedAt?: components["schemas"]["sentAt"];
        };
        /**
         * Format: date-time
         * @description Date and time when the message was sent.
         */
        sentAt: string;
        dynamicCommandResponsePayload: {
            /** @description Indicates whether the command was executed successfully. */
            success: boolean;
            /** @description Human-readable message about the command execution result. */
            message?: string;
            executedAt?: components["schemas"]["sentAt"];
            /** @description The dynamic address where this response was sent. */
            dynamicAddress?: string;
        };
        heartbeatPayload: {
            timestamp: components["schemas"]["sentAt"];
            /** @description Server timestamp in milliseconds since Unix epoch. */
            serverTime?: number;
            /** @description Monotonically increasing sequence number for heartbeat messages. */
            sequenceNumber: number;
        };
    };
    messages: {
        /**
         * Light measured
         * Inform about environmental lighting conditions of a particular streetlight.
         */
        lightMeasured: {
            name: "lightMeasured";
            payload?: components["schemas"]["lightMeasuredPayload"];
            headers: {
                "my-app-header"?: number;
                /** @description Address to reply to */
                replyTo?: string;
                /** @description Correlation identifier for request/reply matching. */
                reqid: string;
            };
            contentType: "application/json";
            correlationId: {
                location: "$message.header#/reqid";
                description: "Correlation ID.";
            };
        };
        /**
         * Light measurement acknowledgment
         * Acknowledgment response for received light measurement data.
         */
        lightMeasuredResponse: {
            name: "lightMeasuredResponse";
            payload?: components["schemas"]["measurementResponsePayload"];
            headers?: components["messageTraits"]["optionalReplyHeaders"]["headers"];
            contentType: "application/json";
            correlationId: {
                location: "$message.header#/reqid";
                description: "Correlation ID.";
            };
        };
        /**
         * Turn on/off
         * Command a particular streetlight to turn the lights on or off.
         */
        turnOnOff: {
            name: "turnOnOff";
            payload?: components["schemas"]["turnOnOffPayload"];
            headers: {
                "my-app-header"?: number;
                /** @description Address to reply to */
                replyTo?: string;
                /** @description Correlation identifier for request/reply matching. */
                reqid: string;
            };
            correlationId: {
                location: "$message.header#/reqid";
                description: "Correlation ID.";
            };
        };
        /**
         * Dim light
         * Command a particular streetlight to dim the lights.
         */
        dimLight: {
            name: "dimLight";
            payload?: components["schemas"]["dimLightPayload"];
            headers: {
                "my-app-header"?: number;
                /** @description Address to reply to */
                replyTo?: string;
                /** @description Correlation identifier for request/reply matching. */
                reqid: string;
            };
            correlationId: {
                location: "$message.header#/reqid";
                description: "Correlation ID.";
            };
        };
        /**
         * Command response
         * Response to a command execution with status and details.
         */
        commandResponse: {
            name: "commandResponse";
            payload?: components["schemas"]["commandResponsePayload"];
            headers?: components["messageTraits"]["commonHeaders"]["headers"];
            contentType: "application/json";
        };
        /**
         * Dynamic command response
         * Response sent to a dynamically determined address.
         */
        dynamicCommandResponse: {
            name: "dynamicCommandResponse";
            payload: components["schemas"]["dynamicCommandResponsePayload"];
            headers?: components["messageTraits"]["optionalReplyHeaders"]["headers"];
            contentType: "application/json";
            correlationId: components["correlationIds"]["reqid"];
        };
        /**
         * Server heartbeat
         * Periodic heartbeat message sent by the server to verify connection health.
         */
        heartbeat: {
            name: "heartbeat";
            payload: components["schemas"]["heartbeatPayload"];
            headers?: components["messageTraits"]["commonHeaders"]["headers"];
            contentType: "application/json";
        };
    };
    parameters: {
        /**
         * @description The ID of the streetlight.
         * @enum {unknown}
         */
        streetlightId: {
            location: "$message.payload#/item/id";
            enum: [
                "streetlight-1",
                "streetlight-2"
            ];
        };
    };
    securitySchemes: {
        bearerAuth: {
            type: "http";
            description: "Bearer token authentication";
        };
    };
    servers: {
        "events-test": {
            host: "test-events.example.com";
            protocol: "ws";
            description: "Test WebSocket server for events (lighting measurements)";
        };
        "commands-prod": {
            host: "prod-commands.example.com";
            protocol: "wss";
            description: "Production WebSocket server for commands (turn on/off, dim) secured with TLS";
        };
    };
    messageTraits: {
        correlationId: {
            correlationId: {
                location: "$message.header#/reqid";
                description: "Correlation ID for request-reply matching, extracted from message header.";
            };
        };
        commonHeaders: {
            headers?: {
                "my-app-header"?: number;
                /** @description Address to reply to */
                replyTo?: string;
            };
        };
        optionalReplyHeaders: {
            headers?: {
                /** @description Address to reply to */
                replyTo?: string;
                /** @description Correlation identifier for request/reply matching. */
                reqid?: string;
            };
        };
    };
    operationTraits: {
        websocket: {
            bindings: unknown;
        };
    };
    replyAddresses: {
        /** @description Reply address extracted from message header replyTo field */
        turnOnReplyAddress: {
            location: "$message.header#/replyTo";
            description: "Reply address extracted from message header replyTo field";
        };
        /** @description Reply address extracted from message payload responseAddress field */
        dimLightReplyAddress: {
            location: "$message.payload#/responseAddress";
            description: "Reply address extracted from message payload responseAddress field";
        };
    };
    correlationIds: {
        /** @description Request ID. */
        reqid: {
            location: "$message.header#/reqid";
            description: "Request ID.";
        };
    };
}
type ReadonlyArray<T> = [
    Exclude<T, undefined>
] extends [
    unknown[]
] ? Readonly<Exclude<T, undefined>> : Readonly<Exclude<T, undefined>[]>;
export const turnOnOffPayloadCommandValues: ReadonlyArray<components["schemas"]["turnOnOffPayload"]["command"]> = ["on", "off"];
