name: E2E Suite

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - main

jobs:
  e2e:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    name: E2E Tests
    env:
      NPM_PUBLISH_REGISTRY: 'http://localhost:4873'
      UNSAFE_HTTP_WHITELIST: 'localhost'
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js 20.x
        uses: actions/setup-node@v4
        with:
          cache: 'yarn'
          node-version: 20.12.2

      - name: Install Dependencies
        run: yarn install --immutable

      - name: Build
        run: yarn build --filter "@openapi-qraft/*"

      - name: Copy Playground for E2E Tests
        run: |
          mkdir -p "$TEST_PROJECTS_DIR"
          cp -r playground "$TEST_PROJECTS_DIR"
          cp -a e2e/projects/. "$TEST_PROJECTS_DIR/"
        env:
          TEST_PROJECTS_DIR: "${{ runner.temp }}/projects"

      - name: Remove Verdaccio Storage
        run: rm -rf e2e/verdaccio-storage

      - name: Publish to Private Registry
        run: yarn run "e2e:publish-to-private-registry"

      - name: Update Projects from Private Registry
        run: TEST_PROJECTS_DIR=${{ runner.temp }}/projects yarn run "e2e:update-projects-from-private-registry"

      - name: Build E2E Projects
        run: TEST_PROJECTS_DIR=${{ runner.temp }}/projects yarn run "e2e:build-projects"