name: Release

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Changesets Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          fetch-tags: true

      - name: list Git Tags
        run: git tag

      - name: Setup Node.js 18.x
        uses: actions/setup-node@v4
        with:
          cache: 'yarn'
          node-version: 18.x

      - name: Install Dependencies
        run: yarn install --immutable

      - name: Create tags
        run: yarn changeset tag

